# San Francisco Bay Area Shop / Other Mode Choice {#other-purpose-chapter}
```{r setup}
library(tidyverse)
library(haven)
library(mlogit)
library(modelsummary)
```

[Chapter 7](#other-purpose-chapter)

## Introduction


```{r sf_nonwork, eval = FALSE} 
sf_shopother_raw <- read_spss("data-raw/Shopping Trips/SPSS/MTC Shopping v2.SAV") 
  #mutate(altname = as_factor(ALTID, levels = "labels"))
sf_shopother <- dfidx(sf_shopother_raw, idx = c("CASENUM", "ALTID"))

# write to data/ folder for future use
write_rds(sf_shopother, "data/shopother.rds")

```


```{r myshape, eval = FALSE} 
myshape <- st_read("data/some_shapefile.shp")
```


```{r model_estimation}
models <- list()
models[['Bivariate']] <- lm(Girth ~ Height, data = trees)
models[['Multivariate']] <- lm(Girth ~ Height + Volume, data = trees)
```

```{r model-comparison}
modelsummary(models, title = "Model Comparison")
```


Table \@ref(tab:model-comparison) shows the estimated models. Figure \@ref(fig:group-mean-plot)
shows the grouped mean for three groups.

```{r group-mean}
# Generate some sample data, then compute mean and standard deviation
# in each group
df <- data.frame(
  gp = factor(rep(letters[1:3], each = 10)),
  y = rnorm(30)
)
ds <- do.call(rbind, lapply(split(df, df$gp), function(d) {
  data.frame(mean = mean(d$y), sd = sd(d$y), gp = d$gp)
}))
```


```{r group-mean-plot, fig.cap="Grouped means."}
# The summary data frame ds is used to plot larger red points on top
# of the raw data. Note that we don't need to supply `data` or `mapping`
# in each layer because the defaults from ggplot() are used.
ggplot(df, aes(gp, y)) +
  geom_point() +
  geom_point(data = ds, aes(y = mean), colour = 'red', size = 3) 
```


## Specification for Shop/Other Mode Choice Model




## Initial Model Specification


## Exploring Alternative Specifications


