<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 The Multinomial Logit Model | A Self-Instructing Course in Mode Choice Modeling</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 The Multinomial Logit Model | A Self-Instructing Course in Mode Choice Modeling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 The Multinomial Logit Model | A Self-Instructing Course in Mode Choice Modeling" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  



<meta name="date" content="2021-05-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="utility-based-choice-theory.html"/>
<link rel="next" href="estimation-chapter.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Self-Instructing Course in Mode Choice Modeling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Foreword</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#original-acknowledgements"><i class="fa fa-check"></i>Original Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-packages"><i class="fa fa-check"></i>R Packages</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="chapter1.html"><a href="chapter1.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chapter1.html"><a href="chapter1.html#background"><i class="fa fa-check"></i><b>1.1</b> Background</a></li>
<li class="chapter" data-level="1.2" data-path="chapter1.html"><a href="chapter1.html#use-of-disaggregate-discrete-choice-models"><i class="fa fa-check"></i><b>1.2</b> Use of Disaggregate Discrete Choice Models</a></li>
<li class="chapter" data-level="1.3" data-path="chapter1.html"><a href="chapter1.html#application-context-in-current-course"><i class="fa fa-check"></i><b>1.3</b> Application Context in Current Course</a></li>
<li class="chapter" data-level="1.4" data-path="chapter1.html"><a href="chapter1.html#urban-and-intercity-travel-mode-choice-modeling"><i class="fa fa-check"></i><b>1.4</b> Urban and Intercity Travel Mode Choice Modeling</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="chapter1.html"><a href="chapter1.html#urban-travel-mode-choice-modeling"><i class="fa fa-check"></i><b>1.4.1</b> Urban Travel Mode Choice Modeling</a></li>
<li class="chapter" data-level="1.4.2" data-path="chapter1.html"><a href="chapter1.html#intercity-mode-choice-models"><i class="fa fa-check"></i><b>1.4.2</b> Intercity Mode Choice Models</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="chapter1.html"><a href="chapter1.html#description-of-the-course"><i class="fa fa-check"></i><b>1.5</b> Description of the Course</a></li>
<li class="chapter" data-level="1.6" data-path="chapter1.html"><a href="chapter1.html#organization-of-the-course-structure"><i class="fa fa-check"></i><b>1.6</b> Organization of the Course Structure</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="elements-of-the-choice-decision-process.html"><a href="elements-of-the-choice-decision-process.html"><i class="fa fa-check"></i><b>2</b> Elements of the Choice Decision Process</a>
<ul>
<li class="chapter" data-level="2.1" data-path="elements-of-the-choice-decision-process.html"><a href="elements-of-the-choice-decision-process.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="elements-of-the-choice-decision-process.html"><a href="elements-of-the-choice-decision-process.html#the-decision-maker"><i class="fa fa-check"></i><b>2.2</b> The Decision Maker</a></li>
<li class="chapter" data-level="2.3" data-path="elements-of-the-choice-decision-process.html"><a href="elements-of-the-choice-decision-process.html#the-alternatives"><i class="fa fa-check"></i><b>2.3</b> The Alternatives</a></li>
<li class="chapter" data-level="2.4" data-path="elements-of-the-choice-decision-process.html"><a href="elements-of-the-choice-decision-process.html#attributes-of-alternatives"><i class="fa fa-check"></i><b>2.4</b> Attributes of Alternatives</a></li>
<li class="chapter" data-level="2.5" data-path="elements-of-the-choice-decision-process.html"><a href="elements-of-the-choice-decision-process.html#the-decision-rule"><i class="fa fa-check"></i><b>2.5</b> The Decision Rule</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="utility-based-choice-theory.html"><a href="utility-based-choice-theory.html"><i class="fa fa-check"></i><b>3</b> Utility-based Choice Theory</a>
<ul>
<li class="chapter" data-level="3.1" data-path="utility-based-choice-theory.html"><a href="utility-based-choice-theory.html#basic-construct-of-utility-theory"><i class="fa fa-check"></i><b>3.1</b> Basic Construct of Utility Theory</a></li>
<li class="chapter" data-level="3.2" data-path="utility-based-choice-theory.html"><a href="utility-based-choice-theory.html#deterministic-choice-concepts"><i class="fa fa-check"></i><b>3.2</b> Deterministic Choice Concepts</a></li>
<li class="chapter" data-level="3.3" data-path="utility-based-choice-theory.html"><a href="utility-based-choice-theory.html#probabilistic-choice-theory"><i class="fa fa-check"></i><b>3.3</b> Probabilistic Choice Theory</a></li>
<li class="chapter" data-level="3.4" data-path="utility-based-choice-theory.html"><a href="utility-based-choice-theory.html#components-of-the-deterministic-portion-of-the-utility-function"><i class="fa fa-check"></i><b>3.4</b> Components of the Deterministic Portion of the Utility Function</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="utility-based-choice-theory.html"><a href="utility-based-choice-theory.html#utility-associated-with-the-attributes-of-alternatives"><i class="fa fa-check"></i><b>3.4.1</b> Utility Associated with the Attributes of Alternatives</a></li>
<li class="chapter" data-level="3.4.2" data-path="utility-based-choice-theory.html"><a href="utility-based-choice-theory.html#utility-biases-due-to-excluded-variables"><i class="fa fa-check"></i><b>3.4.2</b> Utility ‘Biases’ Due to Excluded Variables</a></li>
<li class="chapter" data-level="3.4.3" data-path="utility-based-choice-theory.html"><a href="utility-based-choice-theory.html#utility-related-to-the-characteristics-of-the-decision-maker"><i class="fa fa-check"></i><b>3.4.3</b> Utility Related to the Characteristics of the Decision Maker</a></li>
<li class="chapter" data-level="3.4.4" data-path="utility-based-choice-theory.html"><a href="utility-based-choice-theory.html#utility-defined-by-interactions-between-alternative-attributes-and-decision-maker-characteristics"><i class="fa fa-check"></i><b>3.4.4</b> Utility Defined by Interactions between Alternative Attributes and Decision Maker Characteristics</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="utility-based-choice-theory.html"><a href="utility-based-choice-theory.html#additive-error-term"><i class="fa fa-check"></i><b>3.5</b> Specification of the Additive Error Term</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html"><i class="fa fa-check"></i><b>4</b> The Multinomial Logit Model</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#overview-description-and-functional-form"><i class="fa fa-check"></i><b>4.1</b> Overview Description and Functional Form</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#the-sigmoid-or-s-shape-of-multinomial-logit-probabilities"><i class="fa fa-check"></i><b>4.1.1</b> The Sigmoid or S shape of Multinomial Logit Probabilities</a></li>
<li class="chapter" data-level="4.1.2" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#the-equivalent-differences-property"><i class="fa fa-check"></i><b>4.1.2</b> The Equivalent Differences Property</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#IIA-section"><i class="fa fa-check"></i><b>4.2</b> Independence of Irrelevant Alternatives Property</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#bus-paradox"><i class="fa fa-check"></i><b>4.2.1</b> The Red Bus/Blue Bus Paradox</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#example-prediction-with-multinomial-logit-model"><i class="fa fa-check"></i><b>4.3</b> Example: Prediction with Multinomial Logit Model</a></li>
<li class="chapter" data-level="4.4" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#measures-of-response-to-changes-in-attributes-of-alternatives"><i class="fa fa-check"></i><b>4.4</b> Measures of Response to Changes in Attributes of Alternatives</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#derivatives-of-choice-probabilities"><i class="fa fa-check"></i><b>4.4.1</b> Derivatives of Choice Probabilities</a></li>
<li class="chapter" data-level="4.4.2" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#elasticities-of-choice-probabilities"><i class="fa fa-check"></i><b>4.4.2</b> Elasticities of Choice Probabilities</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#measures-of-responses-to-changes-in-decision-maker-characteristics"><i class="fa fa-check"></i><b>4.5</b> Measures of Responses to Changes in Decision Maker Characteristics</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#derivatives-of-choice-probabilities-1"><i class="fa fa-check"></i><b>4.5.1</b> Derivatives of Choice Probabilities</a></li>
<li class="chapter" data-level="4.5.2" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#elasticities-of-choice-probabilities-1"><i class="fa fa-check"></i><b>4.5.2</b> Elasticities of Choice Probabilities</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#model-estimation-concept-and-method"><i class="fa fa-check"></i><b>4.6</b> Model Estimation: Concept and Method</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#graphical-representation-of-model-estimation"><i class="fa fa-check"></i><b>4.6.1</b> Graphical Representation of Model Estimation</a></li>
<li class="chapter" data-level="4.6.2" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#maximum-likelihood-estimation-theory"><i class="fa fa-check"></i><b>4.6.2</b> Maximum Likelihood Estimation Theory</a></li>
<li class="chapter" data-level="4.6.3" data-path="the-multinomial-logit-model.html"><a href="the-multinomial-logit-model.html#example-of-maximum-likelihood-estimation"><i class="fa fa-check"></i><b>4.6.3</b> Example of Maximum Likelihood Estimation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estimation-chapter.html"><a href="estimation-chapter.html"><i class="fa fa-check"></i><b>5</b> Data Assembly and Estimation of Simple Multinomial Logit Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estimation-chapter.html"><a href="estimation-chapter.html#estimation-intro"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="estimation-chapter.html"><a href="estimation-chapter.html#estimation-data"><i class="fa fa-check"></i><b>5.2</b> Data Requirements Overview</a></li>
<li class="chapter" data-level="5.3" data-path="estimation-chapter.html"><a href="estimation-chapter.html#estimation-collection-methods-traveller"><i class="fa fa-check"></i><b>5.3</b> Sources and Methods for Traveler and Trip Related Data Collection</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="estimation-chapter.html"><a href="estimation-chapter.html#estimation-survey-types"><i class="fa fa-check"></i><b>5.3.1</b> Travel Survey Types</a></li>
<li class="chapter" data-level="5.3.2" data-path="estimation-chapter.html"><a href="estimation-chapter.html#estimation-survey-considerations"><i class="fa fa-check"></i><b>5.3.2</b> Sampling Design Considerations</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="estimation-chapter.html"><a href="estimation-chapter.html#estimation-collection-methods"><i class="fa fa-check"></i><b>5.4</b> Methods for Collecting Mode Related Data</a></li>
<li class="chapter" data-level="5.5" data-path="estimation-chapter.html"><a href="estimation-chapter.html#estimation-data-structure"><i class="fa fa-check"></i><b>5.5</b> Data Structure for Estimation</a></li>
<li class="chapter" data-level="5.6" data-path="estimation-chapter.html"><a href="estimation-chapter.html#estimation-sf-work-data"><i class="fa fa-check"></i><b>5.6</b> Application Data for Work Mode Choice in the San Francisco Bay Area</a></li>
<li class="chapter" data-level="5.7" data-path="estimation-chapter.html"><a href="estimation-chapter.html#estimation-basic"><i class="fa fa-check"></i><b>5.7</b> Estimation of MNL Model with Basic Specification</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="estimation-chapter.html"><a href="estimation-chapter.html#informal-tests"><i class="fa fa-check"></i><b>5.7.1</b> Informal Tests</a></li>
<li class="chapter" data-level="5.7.2" data-path="estimation-chapter.html"><a href="estimation-chapter.html#overall-goodness-of-fit-measures"><i class="fa fa-check"></i><b>5.7.2</b> Overall Goodness-of-Fit Measures</a></li>
<li class="chapter" data-level="5.7.3" data-path="estimation-chapter.html"><a href="estimation-chapter.html#statistical-tests"><i class="fa fa-check"></i><b>5.7.3</b> Statistical Tests</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="estimation-chapter.html"><a href="estimation-chapter.html#estimation-value-of-time"><i class="fa fa-check"></i><b>5.8</b> Value of Time</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="estimation-chapter.html"><a href="estimation-chapter.html#value-of-time-for-linear-utility-function"><i class="fa fa-check"></i><b>5.8.1</b> Value of Time for Linear Utility Function</a></li>
<li class="chapter" data-level="5.8.2" data-path="estimation-chapter.html"><a href="estimation-chapter.html#section5-8-2"><i class="fa fa-check"></i><b>5.8.2</b> Value of Time when Cost is Interacted with another Variable</a></li>
<li class="chapter" data-level="5.8.3" data-path="estimation-chapter.html"><a href="estimation-chapter.html#value-of-time-for-time-or-cost-transformation"><i class="fa fa-check"></i><b>5.8.3</b> Value of Time for Time or Cost Transformation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="specification-chapter.html"><a href="specification-chapter.html"><i class="fa fa-check"></i><b>6</b> Model Specification Refinement: San Francisco Bay Area Work Mode Choice</a>
<ul>
<li class="chapter" data-level="6.1" data-path="specification-chapter.html"><a href="specification-chapter.html#introduction-1"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="specification-chapter.html"><a href="specification-chapter.html#alternative-specifications"><i class="fa fa-check"></i><b>6.2</b> Alternative Specifications</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="specification-chapter.html"><a href="specification-chapter.html#refinement-of-specification-for-alternative-specific-income-effects"><i class="fa fa-check"></i><b>6.2.1</b> Refinement of Specification for Alternative Specific Income Effects</a></li>
<li class="chapter" data-level="6.2.2" data-path="specification-chapter.html"><a href="specification-chapter.html#different-specifications-of-travel-time"><i class="fa fa-check"></i><b>6.2.2</b> Different Specifications of Travel Time</a></li>
<li class="chapter" data-level="6.2.3" data-path="specification-chapter.html"><a href="specification-chapter.html#including-additinal-decision-maker-related-variables"><i class="fa fa-check"></i><b>6.2.3</b> Including Additinal Decision Maker Related Variables</a></li>
<li class="chapter" data-level="6.2.4" data-path="specification-chapter.html"><a href="specification-chapter.html#section6-2-4"><i class="fa fa-check"></i><b>6.2.4</b> Including Trip Context variables</a></li>
<li class="chapter" data-level="6.2.5" data-path="specification-chapter.html"><a href="specification-chapter.html#section6-2-5"><i class="fa fa-check"></i><b>6.2.5</b> Interactions between Trip maker and/or Context Characteristics and Mode Attributes</a></li>
<li class="chapter" data-level="6.2.6" data-path="specification-chapter.html"><a href="specification-chapter.html#additional-model-refinement"><i class="fa fa-check"></i><b>6.2.6</b> Additional Model Refinement</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="specification-chapter.html"><a href="specification-chapter.html#market-segmentation"><i class="fa fa-check"></i><b>6.3</b> Market Segmentation</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="specification-chapter.html"><a href="specification-chapter.html#market-segmentation-tests"><i class="fa fa-check"></i><b>6.3.1</b> Market Segmentation Tests</a></li>
<li class="chapter" data-level="6.3.2" data-path="specification-chapter.html"><a href="specification-chapter.html#market-segmentation-example"><i class="fa fa-check"></i><b>6.3.2</b> Market Segmentation Example</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="specification-chapter.html"><a href="specification-chapter.html#summary"><i class="fa fa-check"></i><b>6.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="other-purpose-chapter.html"><a href="other-purpose-chapter.html"><i class="fa fa-check"></i><b>7</b> San Francisco Bay Area Shop / Other Mode Choice</a>
<ul>
<li class="chapter" data-level="7.1" data-path="other-purpose-chapter.html"><a href="other-purpose-chapter.html#introduction-2"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="other-purpose-chapter.html"><a href="other-purpose-chapter.html#specification-for-shopother-mode-choice-model"><i class="fa fa-check"></i><b>7.2</b> Specification for Shop/Other Mode Choice Model</a></li>
<li class="chapter" data-level="7.3" data-path="other-purpose-chapter.html"><a href="other-purpose-chapter.html#initial-model-specification"><i class="fa fa-check"></i><b>7.3</b> Initial Model Specification</a></li>
<li class="chapter" data-level="7.4" data-path="other-purpose-chapter.html"><a href="other-purpose-chapter.html#exploring-alternative-specifications"><i class="fa fa-check"></i><b>7.4</b> Exploring Alternative Specifications</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="nestedlogit-chapter.html"><a href="nestedlogit-chapter.html"><i class="fa fa-check"></i><b>8</b> Nested Logit Model</a>
<ul>
<li class="chapter" data-level="8.1" data-path="nestedlogit-chapter.html"><a href="nestedlogit-chapter.html#motivation"><i class="fa fa-check"></i><b>8.1</b> Motivation</a></li>
<li class="chapter" data-level="8.2" data-path="nestedlogit-chapter.html"><a href="nestedlogit-chapter.html#formulation-of-nested-logit-model"><i class="fa fa-check"></i><b>8.2</b> Formulation of Nested Logit Model</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="nestedlogit-chapter.html"><a href="nestedlogit-chapter.html#logsum-param"><i class="fa fa-check"></i><b>8.2.1</b> Interpretation of the Logsum Parameter</a></li>
<li class="chapter" data-level="8.2.2" data-path="nestedlogit-chapter.html"><a href="nestedlogit-chapter.html#disaggregate-direct-and-cross-elasticities"><i class="fa fa-check"></i><b>8.2.2</b> Disaggregate Direct and Cross-Elasticities</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="nestedlogit-chapter.html"><a href="nestedlogit-chapter.html#nesting-structures"><i class="fa fa-check"></i><b>8.3</b> Nesting Structures</a></li>
<li class="chapter" data-level="8.4" data-path="nestedlogit-chapter.html"><a href="nestedlogit-chapter.html#testing-NL-structures"><i class="fa fa-check"></i><b>8.4</b> Statistical Testing of Nested Logit Structures</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="nesting-selection-chapter.html"><a href="nesting-selection-chapter.html"><i class="fa fa-check"></i><b>9</b> Selecting a Preferred Nesting Structure</a>
<ul>
<li class="chapter" data-level="9.1" data-path="nesting-selection-chapter.html"><a href="nesting-selection-chapter.html#introduction-3"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="nesting-selection-chapter.html"><a href="nesting-selection-chapter.html#nested-models-for-work-trips"><i class="fa fa-check"></i><b>9.2</b> Nested Models for Work Trips</a></li>
<li class="chapter" data-level="9.3" data-path="nesting-selection-chapter.html"><a href="nesting-selection-chapter.html#nested-models-for-shop-other-trips"><i class="fa fa-check"></i><b>9.3</b> Nested Models for Shop / Other Trips</a></li>
<li class="chapter" data-level="9.4" data-path="nesting-selection-chapter.html"><a href="nesting-selection-chapter.html#practical-issues-and-implications"><i class="fa fa-check"></i><b>9.4</b> Practical Issues and Implications</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="multiple-maxima-in-nested-logit-estimation-nesting-optima-chapter.html"><a href="multiple-maxima-in-nested-logit-estimation-nesting-optima-chapter.html"><i class="fa fa-check"></i><b>10</b> Multiple Maxima in Nested Logit Estimation (#nesting-optima-chapter)</a></li>
<li class="chapter" data-level="11" data-path="aggregate-forecasting-assessment-and-application.html"><a href="aggregate-forecasting-assessment-and-application.html"><i class="fa fa-check"></i><b>11</b> Aggregate Forecasting Assessment, and Application</a>
<ul>
<li class="chapter" data-level="11.1" data-path="aggregate-forecasting-assessment-and-application.html"><a href="aggregate-forecasting-assessment-and-application.html#background-1"><i class="fa fa-check"></i><b>11.1</b> Background</a></li>
<li class="chapter" data-level="11.2" data-path="aggregate-forecasting-assessment-and-application.html"><a href="aggregate-forecasting-assessment-and-application.html#aggregate-forecasting"><i class="fa fa-check"></i><b>11.2</b> Aggregate Forecasting</a></li>
<li class="chapter" data-level="11.3" data-path="aggregate-forecasting-assessment-and-application.html"><a href="aggregate-forecasting-assessment-and-application.html#aggregate-assessment-of-travel-mode-choice-models"><i class="fa fa-check"></i><b>11.3</b> Aggregate Assessment of Travel Mode Choice Models</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="recent-advances-in-discrete-choice-modeling.html"><a href="recent-advances-in-discrete-choice-modeling.html"><i class="fa fa-check"></i><b>12</b> Recent Advances in Discrete Choice Modeling</a>
<ul>
<li class="chapter" data-level="12.1" data-path="recent-advances-in-discrete-choice-modeling.html"><a href="recent-advances-in-discrete-choice-modeling.html#the-gev-class-of-models"><i class="fa fa-check"></i><b>12.1</b> The GEV Class of Models</a></li>
<li class="chapter" data-level="12.2" data-path="recent-advances-in-discrete-choice-modeling.html"><a href="recent-advances-in-discrete-choice-modeling.html#the-mmnl-class-of-models"><i class="fa fa-check"></i><b>12.2</b> The MMNL Class of Models</a></li>
<li class="chapter" data-level="12.3" data-path="recent-advances-in-discrete-choice-modeling.html"><a href="recent-advances-in-discrete-choice-modeling.html#the-mixed-gev-class-of-models"><i class="fa fa-check"></i><b>12.3</b> The Mixed GEV Class of Models</a></li>
<li class="chapter" data-level="12.4" data-path="recent-advances-in-discrete-choice-modeling.html"><a href="recent-advances-in-discrete-choice-modeling.html#summary-1"><i class="fa fa-check"></i><b>12.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Self-Instructing Course in Mode Choice Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-multinomial-logit-model" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> The Multinomial Logit Model</h1>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="the-multinomial-logit-model.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.3     ✓ purrr   0.3.4
## ✓ tibble  3.1.1     ✓ dplyr   1.0.5
## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
## ✓ readr   1.4.0     ✓ forcats 0.5.1</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="the-multinomial-logit-model.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;kableExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="the-multinomial-logit-model.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#&#39; Create a tibble object that evaluates the named expressions passed</span></span>
<span id="cb11-2"><a href="the-multinomial-logit-model.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&#39; in as utility equation.</span></span>
<span id="cb11-3"><a href="the-multinomial-logit-model.html#cb11-3" aria-hidden="true" tabindex="-1"></a>utility_table <span class="ot">&lt;-</span> <span class="cf">function</span>(expressions){</span>
<span id="cb11-4"><a href="the-multinomial-logit-model.html#cb11-4" aria-hidden="true" tabindex="-1"></a>  top <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb11-5"><a href="the-multinomial-logit-model.html#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Alternative =</span> <span class="fu">names</span>(expressions),</span>
<span id="cb11-6"><a href="the-multinomial-logit-model.html#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Expression =</span> expressions </span>
<span id="cb11-7"><a href="the-multinomial-logit-model.html#cb11-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="the-multinomial-logit-model.html#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="the-multinomial-logit-model.html#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb11-10"><a href="the-multinomial-logit-model.html#cb11-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">Value =</span> <span class="fu">eval</span>(<span class="fu">parse</span>(<span class="at">text =</span> Expression)),</span>
<span id="cb11-11"><a href="the-multinomial-logit-model.html#cb11-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">Exponent =</span> <span class="fu">exp</span>(Value) </span>
<span id="cb11-12"><a href="the-multinomial-logit-model.html#cb11-12" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb11-13"><a href="the-multinomial-logit-model.html#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-14"><a href="the-multinomial-logit-model.html#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>( <span class="at">Probability =</span> Exponent <span class="sc">/</span> <span class="fu">sum</span>(Exponent) )</span>
<span id="cb11-15"><a href="the-multinomial-logit-model.html#cb11-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-16"><a href="the-multinomial-logit-model.html#cb11-16" aria-hidden="true" tabindex="-1"></a>  bottom <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb11-17"><a href="the-multinomial-logit-model.html#cb11-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">Alternative =</span> <span class="st">&quot;Total&quot;</span>,</span>
<span id="cb11-18"><a href="the-multinomial-logit-model.html#cb11-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">Expression =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb11-19"><a href="the-multinomial-logit-model.html#cb11-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">Value =</span> <span class="cn">NA</span>,</span>
<span id="cb11-20"><a href="the-multinomial-logit-model.html#cb11-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">Exponent =</span> <span class="fu">sum</span>(top<span class="sc">$</span>Exponent),</span>
<span id="cb11-21"><a href="the-multinomial-logit-model.html#cb11-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">Probability =</span> <span class="fu">sum</span>(top<span class="sc">$</span>Probability)</span>
<span id="cb11-22"><a href="the-multinomial-logit-model.html#cb11-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-23"><a href="the-multinomial-logit-model.html#cb11-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-24"><a href="the-multinomial-logit-model.html#cb11-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(top, bottom)</span>
<span id="cb11-25"><a href="the-multinomial-logit-model.html#cb11-25" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div id="overview-description-and-functional-form" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Overview Description and Functional Form</h2>
<p>The mathematical form of a discrete choice model is determined by the
assumptions made regarding the error components of the utility function for each
alternative as described in section 3.5. The specific assumptions that lead to
the Multinomial Logit Model are (1) the error components are extreme-value (or
Gumbel) distributed, (2) the error components are identically and independently
distributed across alternatives, and (3) the error components are identically
and independently distributed across observations/individuals. We discuss each
of these assumptions below.</p>
<p>The most common assumption for error distributions in the statistical and
modeling literature is that errors are distributed normally. There are good
theoretical and practical reasons for using the normal distribution for many
modeling applications. However, in the case of choice models the normal
distribution assumption for error terms leads to the Multinomial Probit Model
(MNP) which has some properties that make it difficult to use in choice
analysis.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> The Gumbel distribution is selected because it
has computational advantages in a context where maximization is important,
closely approximates the normal distribution (see Figure <a href="the-multinomial-logit-model.html#fig:gumbelpdf">4.1</a>
and Figure <a href="the-multinomial-logit-model.html#fig:gumbelcdf">4.2</a>) and
produces a closed-form<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> probabilistic choice model.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="the-multinomial-logit-model.html#cb12-1" aria-hidden="true" tabindex="-1"></a>pdf <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb12-2"><a href="the-multinomial-logit-model.html#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="at">by =</span> <span class="fl">0.01</span>),</span>
<span id="cb12-3"><a href="the-multinomial-logit-model.html#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Normal =</span> <span class="fu">dnorm</span>(x, <span class="at">sd =</span> <span class="fu">sqrt</span>(pi<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="dv">6</span>)),</span>
<span id="cb12-4"><a href="the-multinomial-logit-model.html#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Gumbel =</span> <span class="fu">exp</span>(<span class="sc">-</span>x) <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span>x))</span>
<span id="cb12-5"><a href="the-multinomial-logit-model.html#cb12-5" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb12-6"><a href="the-multinomial-logit-model.html#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="the-multinomial-logit-model.html#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pdf <span class="sc">%&gt;%</span> <span class="fu">gather</span>(<span class="at">key =</span> <span class="st">&quot;Distribution&quot;</span>, <span class="at">value =</span> <span class="st">&quot;Probability&quot;</span>, <span class="sc">-</span>x),</span>
<span id="cb12-8"><a href="the-multinomial-logit-model.html#cb12-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> Probability, <span class="at">color =</span> Distribution)) <span class="sc">+</span></span>
<span id="cb12-9"><a href="the-multinomial-logit-model.html#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb12-10"><a href="the-multinomial-logit-model.html#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:gumbelpdf"></span>
<img src="04-mnl_files/figure-html/gumbelpdf-1.png" alt="Probability density function for normal and Gumbel distributions." width="672" />
<p class="caption">
Figure 4.1: Probability density function for normal and Gumbel distributions.
</p>
</div>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="the-multinomial-logit-model.html#cb13-1" aria-hidden="true" tabindex="-1"></a>cdf <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb13-2"><a href="the-multinomial-logit-model.html#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">5</span>, <span class="at">by =</span> <span class="fl">0.01</span>),</span>
<span id="cb13-3"><a href="the-multinomial-logit-model.html#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Normal =</span> <span class="fu">pnorm</span>(x, <span class="at">sd =</span> <span class="fu">sqrt</span>(pi<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="dv">6</span>)),</span>
<span id="cb13-4"><a href="the-multinomial-logit-model.html#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Gumbel =</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span>x))</span>
<span id="cb13-5"><a href="the-multinomial-logit-model.html#cb13-5" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb13-6"><a href="the-multinomial-logit-model.html#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="the-multinomial-logit-model.html#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cdf <span class="sc">%&gt;%</span> <span class="fu">gather</span>(<span class="at">key =</span> <span class="st">&quot;Distribution&quot;</span>, <span class="at">value =</span> <span class="st">&quot;Probability&quot;</span>, <span class="sc">-</span>x),</span>
<span id="cb13-8"><a href="the-multinomial-logit-model.html#cb13-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> Probability, <span class="at">color =</span> Distribution)) <span class="sc">+</span></span>
<span id="cb13-9"><a href="the-multinomial-logit-model.html#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb13-10"><a href="the-multinomial-logit-model.html#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:gumbelcdf"></span>
<img src="04-mnl_files/figure-html/gumbelcdf-1.png" alt="Cumulative density function for normal and Gumbel distributions." width="672" />
<p class="caption">
Figure 4.2: Cumulative density function for normal and Gumbel distributions.
</p>
</div>
<p>The Gumbel has the following cumulative distribution and probability density
functions:</p>
<p><span class="math display" id="eq:gumbelcumdist">\[\begin{equation}
  F(\epsilon) = e^{e^{-\mu(\epsilon-\eta)}}
  \tag{4.1}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:gumbelprobdens">\[\begin{equation}
  f(\epsilon) = \mu e^{-\mu(\epsilon-\eta)} \times  e^{e^{-\mu(\epsilon-\eta)}}
  \tag{4.2}
\end{equation}\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(\mu\)</span> is the scale parameter which determines the variance of the distribution and</li>
<li><span class="math inline">\(\eta\)</span> is the location (mode) parameter.</li>
</ul>
<p>The mean and variance of the distribution are:</p>
<p><span class="math display" id="eq:meandistribution">\[\begin{equation}
  Mean = \eta + \frac{0.577}{\mu}
  \tag{4.3}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:variancedistribution">\[\begin{equation}
  Variance = \frac{\pi^2}{6\mu^2}
  \tag{4.4}
\end{equation}\]</span></p>
<p>The second and third assumptions state the location and variance of the
distribution just as <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span> indicate the location and variance of
the normal distribution. We will return to the discussion of the independence
between/among alternatives in <a href="#nested-logit-model">CHAPTER 8</a>.</p>
<p>The three assumptions, taken together, lead to the mathematical structure known
as the Multinomial Logit Model (MNL), which gives the choice probabilities of
each alternative as a function of the systematic portion of the utility of all
the alternatives. The general expression for the probability of choosing an
alternative ‘<em>i</em>’ (<em>i = 1,2,.., J</em>) from a set of <em>J</em> alternatives is:</p>
<p><span class="math display" id="eq:mnl">\[\begin{equation}
  Pr(i) = \frac{\exp(V_i)}{\sum_{j=1}^{J}\exp(V_j)}
  \tag{4.5}
\end{equation}\]</span></p>
<p>Where</p>
<ul>
<li><span class="math inline">\(Pr(i)\)</span> is the probability of the decision-make choosing alternative <em>i</em> and</li>
<li><span class="math inline">\(V_j\)</span> is the systematic component of the utility of alternative <em>j</em>.</li>
</ul>
<p>The exponential function is described in Figure <a href="the-multinomial-logit-model.html#fig:viwithexpVi">4.3</a> which shows the relationship
between <span class="math inline">\(\exp(V_i)\)</span> and <span class="math inline">\(V_i\)</span>. Note that <span class="math inline">\(\exp(V_i)\)</span> is always positive and
increases monotonically with <span class="math inline">\(V_i\)</span>.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="the-multinomial-logit-model.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>( <span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>,<span class="dv">3</span>,.<span class="dv">1</span>), <span class="at">y =</span> <span class="fu">exp</span>(x)) <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="the-multinomial-logit-model.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span> </span>
<span id="cb14-3"><a href="the-multinomial-logit-model.html#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb14-4"><a href="the-multinomial-logit-model.html#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="fu">bquote</span>(V[i])) <span class="sc">+</span> </span>
<span id="cb14-5"><a href="the-multinomial-logit-model.html#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="fu">bquote</span>(<span class="fu">exp</span>(V[i]))) <span class="sc">+</span></span>
<span id="cb14-6"><a href="the-multinomial-logit-model.html#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:viwithexpVi"></span>
<img src="04-mnl_files/figure-html/viwithexpVi-1.png" alt="Relationship Between $V_i$ and $\exp(V_i)$" width="672" />
<p class="caption">
Figure 4.3: Relationship Between <span class="math inline">\(V_i\)</span> and <span class="math inline">\(\exp(V_i)\)</span>
</p>
</div>
<p>The multinomial logit (MNL) model has several important properties. We
illustrate these for a case in which the decision maker has three available
alternatives: Drive Alone (DA), Shared Ride (SR), and TRansit (TR). The
probabilities of each alternative are given by modifying equation 4.5 for each
alternative to obtain:</p>
<p><span class="math display" id="eq:prDAformnl">\[\begin{equation}
  Pr(DA) = \frac{\exp(V_{DA})}{\exp(V_{DA}) + \exp(V_{SR}) + \exp(V_{TR})}
  \tag{4.6}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:prSRformnl">\[\begin{equation}
  Pr(SR) = \frac{\exp(V_{SR})}{\exp(V_{DA}) + \exp(V_{SR}) + \exp(V_{TR})}
  \tag{4.7}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:prTRformnl">\[\begin{equation}
  Pr(TR) = \frac{\exp(V_{TR})}{\exp(V_{DA}) + \exp(V_{SR}) + \exp(V_{TR})}
  \tag{4.8}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(Pr(DA)\)</span>, <span class="math inline">\(Pr(SR)\)</span>, and <span class="math inline">\(Pr(TR)\)</span> are the probabilities of the
decision-maker choosing drive alone, shared ride and transit, respectively, and
<span class="math inline">\(V_{DA}\)</span>, <span class="math inline">\(V_{SR}\)</span> and <span class="math inline">\(V_{TR}\)</span> are the systematic components of the utility for
drive alone, shared ride, and transit alternatives, respectively. It is common
to replace these three equations by a single general equation to represent the
probability of any alternative and to simplify the equation by replacing the
explicit summation in the denominator by the summation over alternatives as:</p>
<p><span class="math display" id="eq:mnlprob">\[\begin{equation}
  Pr(i) = \frac{\exp(V_{i})}{\exp(V_{DA}) + \exp(V_{SR}) + \exp(V_{TR})}
  \tag{4.9}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:mnlprobgeneral">\[\begin{equation}
  Pr(i) = \frac{\exp(V_{i})}{\sum_{j=DA,SR,TR}\exp(V_j)}
  \tag{4.10}
\end{equation}\]</span></p>
<p>where <em>i</em> indicates the alternative for which the probability is being computed.</p>
<p>This formulation implies that the probability of choosing an alternative
increases monotonically with an increase in the systematic utility of that
alternative and decreases with increases in the systematic utility of each of
the other alternatives. This is illustrated in Table <a href="the-multinomial-logit-model.html#tab:dralonefordralone">4.1</a> showing the
probability of DA as a function of its own utility (with the utilities of other
alternatives held constant) and in Table <a href="#tab:drloneforshrridetransit"><strong>??</strong></a>
as a function of the utility of other alternatives with its own utility fixed.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="the-multinomial-logit-model.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb15-2"><a href="the-multinomial-logit-model.html#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">case =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,</span>
<span id="cb15-3"><a href="the-multinomial-logit-model.html#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">vda =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.0</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="fl">0.0</span>, <span class="fl">1.5</span>, <span class="fl">3.0</span>),</span>
<span id="cb15-4"><a href="the-multinomial-logit-model.html#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">vsr =</span> <span class="sc">-</span><span class="fl">1.5</span>,</span>
<span id="cb15-5"><a href="the-multinomial-logit-model.html#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">vtr =</span> <span class="sc">-</span><span class="fl">0.5</span></span>
<span id="cb15-6"><a href="the-multinomial-logit-model.html#cb15-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a href="the-multinomial-logit-model.html#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-8"><a href="the-multinomial-logit-model.html#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">p =</span> <span class="fu">exp</span>(vda) <span class="sc">/</span> (<span class="fu">exp</span>(vda) <span class="sc">+</span> <span class="fu">exp</span>(vsr) <span class="sc">+</span> <span class="fu">exp</span>(vtr))</span>
<span id="cb15-9"><a href="the-multinomial-logit-model.html#cb15-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb15-10"><a href="the-multinomial-logit-model.html#cb15-10" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kbl</span>(  </span>
<span id="cb15-11"><a href="the-multinomial-logit-model.html#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Probability Values for Drive Alone as a Function of Drive Alone Utility (Shared Ride and Transit Utilities held constant)&quot;</span>, </span>
<span id="cb15-12"><a href="the-multinomial-logit-model.html#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">&quot;$Case$&quot;</span>, <span class="st">&quot;$V_{DA}$&quot;</span>, <span class="st">&quot;$V_{SR}$&quot;</span>, <span class="st">&quot;$V_{TR}$&quot;</span>, <span class="st">&quot;$Pr(DA)$&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb15-13"><a href="the-multinomial-logit-model.html#cb15-13" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dralonefordralone">Table 4.1: </span>Probability Values for Drive Alone as a Function of Drive Alone Utility (Shared Ride and Transit Utilities held constant)
</caption>
<thead>
<tr>
<th style="text-align:right;">
<span class="math inline">\(Case\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(V_{DA}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(V_{SR}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(V_{TR}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(Pr(DA)\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
-3.0
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
0.0566117
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
0.2119416
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
0.5465494
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1.5
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
0.8437947
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
0.9603322
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="the-multinomial-logit-model.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb16-2"><a href="the-multinomial-logit-model.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">case =</span> <span class="dv">6</span><span class="sc">:</span><span class="dv">11</span>,</span>
<span id="cb16-3"><a href="the-multinomial-logit-model.html#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">vda =</span> <span class="fl">0.0</span>,</span>
<span id="cb16-4"><a href="the-multinomial-logit-model.html#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">vsr =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.5</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="sc">-</span><span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>),</span>
<span id="cb16-5"><a href="the-multinomial-logit-model.html#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">vtr =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">1.5</span>, <span class="sc">-</span><span class="fl">1.0</span>, <span class="sc">-</span><span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="sc">-</span><span class="fl">1.0</span>, <span class="sc">-</span><span class="fl">0.5</span>)</span>
<span id="cb16-6"><a href="the-multinomial-logit-model.html#cb16-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb16-7"><a href="the-multinomial-logit-model.html#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb16-8"><a href="the-multinomial-logit-model.html#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">p =</span> <span class="fu">exp</span>(vda) <span class="sc">/</span> (<span class="fu">exp</span>(vda) <span class="sc">+</span> <span class="fu">exp</span>(vsr) <span class="sc">+</span> <span class="fu">exp</span>(vtr))</span>
<span id="cb16-9"><a href="the-multinomial-logit-model.html#cb16-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb16-10"><a href="the-multinomial-logit-model.html#cb16-10" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kbl</span>(</span>
<span id="cb16-11"><a href="the-multinomial-logit-model.html#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Probability Values for Drive Alone as a Function of Shared Ride and Transit Utilties&quot;</span>, </span>
<span id="cb16-12"><a href="the-multinomial-logit-model.html#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">&quot;$Case$&quot;</span>, <span class="st">&quot;$V_{DA}$&quot;</span>, <span class="st">&quot;$V_{SR}$&quot;</span>, <span class="st">&quot;$V_{TR}$&quot;</span>, <span class="st">&quot;$Pr(DA)$&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-13"><a href="the-multinomial-logit-model.html#cb16-13" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:draloneforshrridetransit">Table 4.2: </span>Probability Values for Drive Alone as a Function of Shared Ride and Transit Utilties
</caption>
<thead>
<tr>
<th style="text-align:right;">
<span class="math inline">\(Case\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(V_{DA}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(V_{SR}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(V_{TR}\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(Pr(DA)\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
0.6914385
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
-1.0
</td>
<td style="text-align:right;">
0.6285317
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
0.5465494
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
0.5465494
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
-1.0
</td>
<td style="text-align:right;">
0.5064804
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
0.4518628
</td>
</tr>
</tbody>
</table>
<p>We use this three-alternative example to illustrate three important properties
of the MNL: (1) its sigmoid or <em>S</em> shape, (2) dependence of the alternative
choice probabilities on the differences in the systematic utility and (3)
independence of the ratio of the choice probabilities of any pair of
alternatives from the attributes and availability of other alternatives.</p>
<div id="the-sigmoid-or-s-shape-of-multinomial-logit-probabilities" class="section level3" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> The Sigmoid or S shape of Multinomial Logit Probabilities</h3>
<p>The <em>S</em> shape of the MNL probabilities is illustrated in Figure
<a href="#tab:choiceprob"><strong>??</strong></a> where the
probability of choosing Drive Alone is shown as a function of its own utility,
with the utilities of the other alternatives held constant. The <em>S</em>-shape
limits the probability range between zero when the utility of DA is very low,
relative to other alternatives, and one when the utility of DA is very high,
relative to other alternatives. This function has very gradual slope at extreme
values of DA utility, relative to the other alternatives, and is much steeper
when its utility reaches a value such that its choice probability is close to
one-half. This implies that if the representative utility of one alternative is
very low or very high, compared with the others, a small increase in the utility
of this alternative will not substantially affect its probability of being
chosen. The point at which an increase in the representative utility of an
alternative has the greatest effect on its probability of being chosen (<em>i.e.</em>,
the point of maximum slope along the curve) is when its representative utility
is equivalent to the combined utility of the other alternatives. When this is
true, a small increase in the utility of one alternative can ‘tip the balance’
and induce a large increase in the probability of the alternative being chosen
(Train, 1993).</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="the-multinomial-logit-model.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#&#39; Function to compute mnl probabilities</span></span>
<span id="cb17-2"><a href="the-multinomial-logit-model.html#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&#39; @param vi utility of target alternative</span></span>
<span id="cb17-3"><a href="the-multinomial-logit-model.html#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&#39; @param ... utilities of other alternatives</span></span>
<span id="cb17-4"><a href="the-multinomial-logit-model.html#cb17-4" aria-hidden="true" tabindex="-1"></a>mnl_prob <span class="ot">&lt;-</span> <span class="cf">function</span>(vi, ...){</span>
<span id="cb17-5"><a href="the-multinomial-logit-model.html#cb17-5" aria-hidden="true" tabindex="-1"></a>  vj <span class="ot">&lt;-</span> <span class="fu">c</span>(...)</span>
<span id="cb17-6"><a href="the-multinomial-logit-model.html#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">exp</span>(vi) <span class="sc">/</span> <span class="fu">sum</span>(<span class="fu">exp</span>(vj))</span>
<span id="cb17-7"><a href="the-multinomial-logit-model.html#cb17-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="the-multinomial-logit-model.html#cb18-1" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb18-2"><a href="the-multinomial-logit-model.html#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">v_da =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="at">by =</span> <span class="fl">0.01</span>),</span>
<span id="cb18-3"><a href="the-multinomial-logit-model.html#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">v_tr =</span> <span class="dv">0</span>, <span class="at">v_walk =</span> <span class="sc">-</span><span class="fl">0.5</span></span>
<span id="cb18-4"><a href="the-multinomial-logit-model.html#cb18-4" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> </span>
<span id="cb18-5"><a href="the-multinomial-logit-model.html#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="the-multinomial-logit-model.html#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-7"><a href="the-multinomial-logit-model.html#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">drive   =</span> <span class="fu">mnl_prob</span>(v_da,   v_da, v_tr, v_walk),</span>
<span id="cb18-8"><a href="the-multinomial-logit-model.html#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">transit =</span> <span class="fu">mnl_prob</span>(v_tr,   v_da, v_tr, v_walk),</span>
<span id="cb18-9"><a href="the-multinomial-logit-model.html#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">walk    =</span> <span class="fu">mnl_prob</span>(v_walk, v_da, v_tr, v_walk)</span>
<span id="cb18-10"><a href="the-multinomial-logit-model.html#cb18-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-11"><a href="the-multinomial-logit-model.html#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="the-multinomial-logit-model.html#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(u <span class="sc">%&gt;%</span> <span class="fu">gather</span>(Mode, Probability, drive, transit, walk), </span>
<span id="cb18-13"><a href="the-multinomial-logit-model.html#cb18-13" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> v_da, <span class="at">y =</span> Probability, <span class="at">color =</span> Mode)) <span class="sc">+</span> </span>
<span id="cb18-14"><a href="the-multinomial-logit-model.html#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb18-15"><a href="the-multinomial-logit-model.html#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Utility of Drive&quot;</span>) <span class="sc">+</span> </span>
<span id="cb18-16"><a href="the-multinomial-logit-model.html#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:choiceprob"></span>
<img src="04-mnl_files/figure-html/choiceprob-1.png" alt="Probability of choosing alternatives while holding other utilities constant, $V_{transit} = 0, V_{walk} = -0.5$" width="672" />
<p class="caption">
Figure 4.4: Probability of choosing alternatives while holding other utilities constant, <span class="math inline">\(V_{transit} = 0, V_{walk} = -0.5\)</span>
</p>
</div>
</div>
<div id="the-equivalent-differences-property" class="section level3" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> The Equivalent Differences Property</h3>
<p>A fundamental property of the multinomial logit and other choice models is that
the choice probabilities of the alternatives depend only on the differences in
the systematic utilities of different alternatives and not their actual values.
This can be illustrated in two ways. First, we show that the choice probability
equations are unchanged if the same incremental value, say <span class="math inline">\(\Delta V\)</span>, is added
to the utility of each alternative. The original probabilities for the three
alternatives in the example are given by:</p>
<p><span class="math display" id="eq:originalprob">\[\begin{equation}
  Pr(i) = \frac{\exp(V_{i})}{\exp(V_{DA}) + \exp(V_{SR}) + \exp(V_{TR})}
  \tag{4.11}
\end{equation}\]</span></p>
<p>where <em>i</em> is the alternative for which the probabilities are being computed.</p>
<p>Adding <span class="math inline">\(\Delta V\)</span> to the systematic components of <span class="math inline">\(V_{DA}\)</span>, <span class="math inline">\(V_{SR}\)</span> and
<span class="math inline">\(V_{TR}\)</span> gives<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>:</p>
<p><span class="math display" id="eq:probdeltav">\[\begin{align*}
  Pr(i)&amp;= \frac{\exp(V_i + {\Delta V })}
  {\exp(V_{DA}+{\Delta V }) + \exp(V_{SR}+{\Delta V }) + \exp(V_{TR}+{\Delta V })} \\
  &amp;= \frac{\exp(V_i) \times \exp({\Delta V })}
  {\exp(V_{DA}) \times \exp({\Delta V }) + \exp(V_{SR}) \times \exp({\Delta V }) +            \exp(V_{TR}) \times \exp({\Delta V })} \\
  &amp;= \frac{\exp(V_i) \times \exp({\Delta V })}{[\exp(V_{DA}) + \exp(V_{SR}) + \exp(V_{TR})] \times \exp({\Delta V })} \\
  &amp;= \frac{\exp(V_i)}{[\exp(V_{DA}) + \exp(V_{SR}) + \exp(V_{TR})]}
  \tag{4.12}
\end{align*}\]</span></p>
<p>which is the same probability as before <span class="math inline">\(\Delta V\)</span> was added to each of the
utilities. This result applies to any value of <span class="math inline">\(\Delta V\)</span>. We also illustrate
this property through use of a numerical example for the three alternative
choice problem used earlier. The following equations represent the case when
the utility values for Drive Alone, Shared Ride and Transit equal 0.5, 1.5 and
3.0, respectively:</p>
<p><span class="math display" id="eq:DAutilityvalues">\[\begin{equation}
  Pr(DA) = \frac {\exp(-0.5)}{\exp(-0.5) + \exp(-1.5) + \exp(-3.0)} = 0.690
  \tag{4.13}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:SRutilityvalues">\[\begin{equation}
  Pr(SR) = \frac {\exp(-1.5)}{\exp(-0.5) + \exp(-1.5) + \exp(-3.0)} = 0.254
  \tag{4.14}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:TRutilityvalues">\[\begin{equation}
  Pr(TR) = \frac {\exp(-3.0)}{\exp(-0.5) + \exp(-1.5) + \exp(-3.0)} = 0.057
  \tag{4.15}
\end{equation}\]</span></p>
<p>Similarly, if the utility of each alternative is increased by one, the
probabilities are:</p>
<p><span class="math display" id="eq:DAplusoneutilityvalues">\[\begin{equation}
  Pr(DA) = \frac {\exp(0.5)}{\exp(0.5) + \exp(-0.5) + \exp(-2.0)} = 0.690
  \tag{4.16}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:SRplusoneutilityvalues">\[\begin{equation}
  Pr(SR) = \frac {\exp(-0.5)}{\exp(0.5) + \exp(-0.5) + \exp(-2.0)} = 0.254
  \tag{4.17}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:TRplusoneutilityvalues">\[\begin{equation}
  Pr(TR) = \frac {\exp(-2.0)}{\exp(0.5) + \exp(-0.5) + \exp(-2.0)} = 0.057
  \tag{4.18}
\end{equation}\]</span></p>
<p>As expected, the choice probabilities are identical to those obtained before the
addition of the constant utility to each mode. The calculations supporting this
comparison are shown in Table 4.3 and Table 4.4. Table 4.3 shows the
computation of the choice probabilities based on the initial set of modal
utilities and Table 4.4 shows the same computation after each of the utilities
is increased by one.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabel4-3">Table 4.3: </span>Numerical Example Illustrating Equivalent Difference Property: Probability of Each Alternative Before Adding Delta
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Utility
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
Alternative
</th>
<th style="text-align:left;">
Expression
</th>
<th style="text-align:right;">
Value
</th>
<th style="text-align:right;">
Exponent
</th>
<th style="text-align:right;">
Probability
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Drive Alone
</td>
<td style="text-align:left;">
-0.50
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
0.6065307
</td>
<td style="text-align:right;">
0.6896721
</td>
</tr>
<tr>
<td style="text-align:left;">
Shared Ride
</td>
<td style="text-align:left;">
-1.50
</td>
<td style="text-align:right;">
-1.5
</td>
<td style="text-align:right;">
0.2231302
</td>
<td style="text-align:right;">
0.2537162
</td>
</tr>
<tr>
<td style="text-align:left;">
Transit
</td>
<td style="text-align:left;">
-3.00
</td>
<td style="text-align:right;">
-3.0
</td>
<td style="text-align:right;">
0.0497871
</td>
<td style="text-align:right;">
0.0566117
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.8794479
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
</tbody>
</table>
<p>where the sum of the exponent variable is equal to 0.879.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabel4-4">Table 4.4: </span>Numerical Example Illustrating Equivalent Difference Property: Probability of Each Alternative After Adding Delta (=1.0)
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Utility
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
Alternative
</th>
<th style="text-align:left;">
Expression
</th>
<th style="text-align:right;">
Value
</th>
<th style="text-align:right;">
Exponent
</th>
<th style="text-align:right;">
Probability
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Drive Alone
</td>
<td style="text-align:left;">
-0.50 + 1.00
</td>
<td style="text-align:right;">
0.5
</td>
<td style="text-align:right;">
1.6487213
</td>
<td style="text-align:right;">
0.6896721
</td>
</tr>
<tr>
<td style="text-align:left;">
Shared Ride
</td>
<td style="text-align:left;">
-1.50 + 1.00
</td>
<td style="text-align:right;">
-0.5
</td>
<td style="text-align:right;">
0.6065307
</td>
<td style="text-align:right;">
0.2537162
</td>
</tr>
<tr>
<td style="text-align:left;">
Transit
</td>
<td style="text-align:left;">
-3.00 + 1.00
</td>
<td style="text-align:right;">
-2.0
</td>
<td style="text-align:right;">
0.1353353
</td>
<td style="text-align:right;">
0.0566117
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
2.3905872
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
</tbody>
</table>
<p>Where the sum of the exponent variable is equal to 2.391</p>
<p>The expression for the probability equation of the logit model (equation 4.9)
can also be presented in a different form which makes the equivalent difference
property more apparent. For the drive alone alternative, this expression can be
obtained by multiplying the numerator and denominator of the standard
probability expression by (-VDA) as shown in the following equations.</p>
<p><span class="math display" id="eq:fournineteen">\[\begin{equation}
\begin{split}
  Pr(DA) &amp;= \frac{\exp(V_{DA})}{\exp(V_{DA}) + \exp(V_{SR}) + \exp(V_{TR})} \times \frac {\exp(-V_{DA})}{\exp(-V_{DA})}\\
  &amp;= \frac {\exp(V_{DA})\times \exp(-V_{DA})}{[\exp(V_{DA}) + \exp(V_{SR}) + \exp(V_{TR})] \times \exp(-V_{DA})}\\
  &amp;= \frac {\exp(0)}{\exp(0) + \exp(V_{SR}-V_{DA}) + \exp(V_{TR}-V_{DA})}
  \end{split}
  \tag{4.19}
\end{equation}\]</span></p>
<p>which simplifies to:</p>
<p><span class="math display" id="eq:fourtwenty">\[\begin{equation}
Pr(i) = \frac{1}{\exp(0) + \exp(V_{SR}-V_{DA}) + \exp(V_{TR}-V_{DA})}
\tag{4.20}
\end{equation}\]</span></p>
<p>This formulation explicitly shows that the probability of the drive alone
alternative is a function of the differences in systematic utility between the
drive alone alternative and each other alternative. This can be applied to the
general case for alternative <span class="math inline">\(i\)</span> which can be represented in terms of the
pairwise difference in its utility and the utility of each of the other
alternatives by the following equation:</p>
<p><span class="math display" id="eq:fourtwentyone">\[\begin{equation}
Pr(i) = \frac{1}{1 + \sum_{j \ne i}\exp(V_j - V_i)}  \qquad \forall i \in J
\tag{4.21}
\end{equation}\]</span></p>
<div id="implication-of-constant-differences-for-alternative-specific-constants-and-variables" class="section level4" number="4.1.2.1">
<h4><span class="header-section-number">4.1.2.1</span> Implication of Constant Differences for Alternative Specific Constants and Variables</h4>
<p>The constant difference property of logit models has an important implication
for the specification of the utilities of the alternatives. Recall that the
systematic portion of the utility of an individual, ‘<span class="math inline">\(t\)</span>,’ and alternative ‘<span class="math inline">\(i\)</span>’
is the sum of decision-maker related bias, mode attribute related utility, and
interactions between these. That is:</p>
<p><span class="math display" id="eq:fourtwentytwo">\[\begin{equation}
V_{DA} = V_{DA}(S_t) + V(X_{DA}) + V(S_t,X_{DA})
\tag{4.22}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:fourtwentythree">\[\begin{equation}
V_{SR} = V_{SR}(S_t) + V(X_{SR}) + V(S_t,X_{SR})
\tag{4.23}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:fourtwentyfour">\[\begin{equation}
V_{TR} = V_{TR}(S_t) + V(X_{TR}) + V(S_t,X_{TR})
\tag{4.24}
\end{equation}\]</span></p>
<p>Each term on the right hand side of each equation can be replaced by an explicit
function of the relevant variables. For example, if the decision-maker
preferences are a function of income, attribute based utility is a function of
travel time and there are no interaction terms, the utility function becomes:</p>
<p><span class="math display" id="eq:fourtwentyfive">\[\begin{equation}
  V_{DA} = \beta_{DA,0} + \beta_{DA,1} \times Income_t + \gamma \times TT_{DA}
\tag{4.25}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:fourtwentysix">\[\begin{equation}
  V_{SR} = \beta_{SR,0} + \beta_{SR,1} \times Income_t + \gamma \times TT_{SR}
\tag{4.26}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:fourtwentyseven">\[\begin{equation}
  V_{TR} = \beta_{TR,0} + \beta_{TR,1} \times Income_t + \gamma \times TT_{TR}
\tag{4.27}
\end{equation}\]</span></p>
<p>and the differences between pairs of alternatives for prediction of DA
probability become:</p>
<p><span class="math display" id="eq:fourtwentyeight">\[\begin{equation}
\begin{split}
  V_{SR} - V_{DA} = (\beta_{SR,0} - \beta_{DA,0}) + \beta_{SR,1} - \beta_{DA,1})\\ \times Income_t + \gamma \times (TT_{SR} - TT_{DA})
\end{split}
\tag{4.28}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:fourtwentynine">\[\begin{equation}
\begin{split}
  V_{TR} - V_{DA} = (\beta_{TR,0} - \beta_{DA,0}) + \beta_{TR,1} - \beta_{DA,1})\\ \times Income_t + \gamma \times (TT_{TR} - TT_{TA})
\end{split}
\tag{4.29}
\end{equation}\]</span></p>
<p>It is not possible to estimate all of the constants; <span class="math inline">\(\beta_{DA,0}\)</span>,
<span class="math inline">\(\beta_{SR,0}\)</span> and <span class="math inline">\(\beta_{TR,0}\)</span>; and all of the income parameters;
<span class="math inline">\(\beta_{DA,1}\)</span>, <span class="math inline">\(\beta_{SR,1}\)</span> and <span class="math inline">\(\beta_{TR,1}\)</span>; in these equations because
adding any algebraic value to each of the constants or to each of the income
parameters does not cause any change in the probabilities of any of the
alternatives. This phenomenon is common to all utility-based choice models and
follows directly from the equivalent differences property discussed above. The
solution to this problem is to place a single constraint on each set of
parameters; in this case, the constants and the income parameters. Any
constraint can be adopted for each set of parameters; however, the simplest and
most widely used is to set the preference related parameters for one
alternative, called the base or reference alternative, to zero and to
re-interpret the remaining parameters to represent preference differences
relative to the base alternative.</p>
<p>The selection of the reference alternative is arbitrary and does not affect the
overall quality or interpretation of the model; however, the equations and the
estimation results will appear to be different. For example, if we set TRansit
as the reference alternative by setting <span class="math inline">\(\beta_{TR,0}\)</span> and <span class="math inline">\(\beta_{TR,1}\)</span> equal
to zero, the utility functions become:</p>
<p><span class="math display" id="eq:fourthirty">\[\begin{equation}
  V_{DA,t} = \beta_{DA-TR,0} + \beta_{DA-TR,1} \times Inc_t + \gamma \times TT_{DA}
\tag{4.30}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:fourthirtyone">\[\begin{equation}
  V_{SR,t} = \beta_{SR-TR,0} + \beta_{SR-TR,1} \times Inc_t + \gamma \times TT_{SR}
\tag{4.31}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:fourthirtytwo">\[\begin{equation}
  V_{TR,t} = \qquad \qquad \qquad 0  \qquad \qquad \qquad + \gamma \times TT_{TR}
\tag{4.32}
\end{equation}\]</span></p>
<p>where the modified notation for the remaining constants and income parameters is
used to emphasize that these parameters are ‘relative to the TRansit
alternative.’ Alternatively, if we select Drive Alone as the reference
alternative, we obtain:</p>
<p><span class="math display" id="eq:fourthirtythree">\[\begin{equation}
  V_{DA,t} = \qquad \qquad \qquad 0  \qquad \qquad \qquad + \gamma \times TT_{DA}
\tag{4.33}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:fourthirtyfour">\[\begin{equation}
  V_{SR,t} = \beta_{SR-DA,0} + \beta_{SR-DA,1} \times Inc_t + \gamma \times TT_{SR}
\tag{4.34}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:fourthirtyfive">\[\begin{equation}
  V_{TR,t} = \beta_{TR-DA,0} + \beta_{TR-DA,1} \times Inc_t + \gamma \times TT_{TR}
\tag{4.35}
\end{equation}\]</span></p>
<p>where the constants and income parameters are relative to the Drive Alone alternative.</p>
<p>These two models are equivalent as shown in Table <a href="#transit-base"><strong>??</strong></a> and Table <a href="#da-base"><strong>??</strong></a> which
correspond to the TRansit reference and Drive Alone reference examples,
respectively, for an individual from a household with $50,000 annual income and
facing travel times of 30, 35 and 50 minutes for Drive Alone, Shared Ride and
TRansit, respectively.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="the-multinomial-logit-model.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">utility_table</span>(</span>
<span id="cb19-2"><a href="the-multinomial-logit-model.html#cb19-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">c</span>(<span class="st">&quot;Drive Alone&quot;</span> <span class="ot">=</span> <span class="st">&quot;1.1 + 0.008 * 50 - 0.02 * 30&quot;</span>,</span>
<span id="cb19-3"><a href="the-multinomial-logit-model.html#cb19-3" aria-hidden="true" tabindex="-1"></a>   <span class="st">&quot;Shared Ride&quot;</span> <span class="ot">=</span> <span class="st">&quot;0.8 + 0.006 * 50 - 0.02 * 35&quot;</span>,</span>
<span id="cb19-4"><a href="the-multinomial-logit-model.html#cb19-4" aria-hidden="true" tabindex="-1"></a>   <span class="st">&quot;Transit&quot;</span> <span class="ot">=</span> <span class="st">&quot;0.0 + 0.000 * 50 - 0.02 * 50&quot;</span>)</span>
<span id="cb19-5"><a href="the-multinomial-logit-model.html#cb19-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb19-6"><a href="the-multinomial-logit-model.html#cb19-6" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">&quot;Utility and Probability calculation with TRansit as Base Alternative&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb19-7"><a href="the-multinomial-logit-model.html#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span></span>
<span id="cb19-8"><a href="the-multinomial-logit-model.html#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">&quot; &quot;</span><span class="ot">=</span><span class="dv">1</span>, <span class="st">&quot;Utility&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">2</span>), <span class="at">align =</span> <span class="st">&quot;center&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:transit-base">Table 4.5: </span>Utility and Probability calculation with TRansit as Base Alternative
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Utility
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
Alternative
</th>
<th style="text-align:left;">
Expression
</th>
<th style="text-align:right;">
Value
</th>
<th style="text-align:right;">
Exponent
</th>
<th style="text-align:right;">
Probability
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Drive Alone
</td>
<td style="text-align:left;">
1.1 + 0.008 * 50 - 0.02 * 30
</td>
<td style="text-align:right;">
0.9
</td>
<td style="text-align:right;">
2.4596031
</td>
<td style="text-align:right;">
0.5694439
</td>
</tr>
<tr>
<td style="text-align:left;">
Shared Ride
</td>
<td style="text-align:left;">
0.8 + 0.006 * 50 - 0.02 * 35
</td>
<td style="text-align:right;">
0.4
</td>
<td style="text-align:right;">
1.4918247
</td>
<td style="text-align:right;">
0.3453852
</td>
</tr>
<tr>
<td style="text-align:left;">
Transit
</td>
<td style="text-align:left;">
0.0 + 0.000 * 50 - 0.02 * 50
</td>
<td style="text-align:right;">
-1.0
</td>
<td style="text-align:right;">
0.3678794
</td>
<td style="text-align:right;">
0.0851709
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
4.3193072
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
</tbody>
</table>
<p>where the sum of the exponent variable equals 4.319.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="the-multinomial-logit-model.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">utility_table</span>(</span>
<span id="cb20-2"><a href="the-multinomial-logit-model.html#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>( <span class="st">&quot;Drive Alone&quot;</span> <span class="ot">=</span> <span class="st">&quot;0.0 + 0.000 * 50 - 0.02 * 30&quot;</span>,</span>
<span id="cb20-3"><a href="the-multinomial-logit-model.html#cb20-3" aria-hidden="true" tabindex="-1"></a>     <span class="st">&quot;Shared Ride&quot;</span> <span class="ot">=</span> <span class="st">&quot;-0.3 - 0.002 * 50 - 0.02 * 35&quot;</span>,</span>
<span id="cb20-4"><a href="the-multinomial-logit-model.html#cb20-4" aria-hidden="true" tabindex="-1"></a>     <span class="st">&quot;Transit&quot;</span> <span class="ot">=</span> <span class="st">&quot;-1.1 - 0.008 * 50 - 0.02 * 50&quot;</span>)</span>
<span id="cb20-5"><a href="the-multinomial-logit-model.html#cb20-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="the-multinomial-logit-model.html#cb20-6" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">&quot;Utility and Probability calculation with TRansit as Base Alternative&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb20-7"><a href="the-multinomial-logit-model.html#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span></span>
<span id="cb20-8"><a href="the-multinomial-logit-model.html#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">&quot; &quot;</span><span class="ot">=</span><span class="dv">1</span>, <span class="st">&quot;Utility&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">2</span>), <span class="at">align =</span> <span class="st">&quot;center&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:da-base">Table 4.6: </span>Utility and Probability calculation with TRansit as Base Alternative
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Utility
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
Alternative
</th>
<th style="text-align:left;">
Expression
</th>
<th style="text-align:right;">
Value
</th>
<th style="text-align:right;">
Exponent
</th>
<th style="text-align:right;">
Probability
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Drive Alone
</td>
<td style="text-align:left;">
0.0 + 0.000 * 50 - 0.02 * 30
</td>
<td style="text-align:right;">
-0.6
</td>
<td style="text-align:right;">
0.5488116
</td>
<td style="text-align:right;">
0.5694439
</td>
</tr>
<tr>
<td style="text-align:left;">
Shared Ride
</td>
<td style="text-align:left;">
-0.3 - 0.002 * 50 - 0.02 * 35
</td>
<td style="text-align:right;">
-1.1
</td>
<td style="text-align:right;">
0.3328711
</td>
<td style="text-align:right;">
0.3453852
</td>
</tr>
<tr>
<td style="text-align:left;">
Transit
</td>
<td style="text-align:left;">
-1.1 - 0.008 * 50 - 0.02 * 50
</td>
<td style="text-align:right;">
-2.5
</td>
<td style="text-align:right;">
0.0820850
</td>
<td style="text-align:right;">
0.0851709
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.9637677
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
</tbody>
</table>
<p>where the sum of the exponent variable equals 0.964.</p>
<p>As expected, the resultant probabilities are identical in both cases. Table 4 7
shows that the differences in the alternative specific constants and income
parameters between alternatives are the same for the TRansit base case and the
Drive Alone base case.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="the-multinomial-logit-model.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb21-2"><a href="the-multinomial-logit-model.html#cb21-2" aria-hidden="true" tabindex="-1"></a> <span class="st">&quot;Alternative&quot;</span><span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Drive Alone&quot;</span>, <span class="st">&quot;Shared Ride&quot;</span>, <span class="st">&quot;Transit&quot;</span>),</span>
<span id="cb21-3"><a href="the-multinomial-logit-model.html#cb21-3" aria-hidden="true" tabindex="-1"></a> <span class="st">&quot;Constant&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;1.1&quot;</span>,<span class="st">&quot;0.8&quot;</span>,<span class="st">&quot;0.0&quot;</span>),</span>
<span id="cb21-4"><a href="the-multinomial-logit-model.html#cb21-4" aria-hidden="true" tabindex="-1"></a> <span class="st">&quot;Income&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;0.008&quot;</span>, <span class="st">&quot;0.006&quot;</span>, <span class="st">&quot;0.000&quot;</span>),</span>
<span id="cb21-5"><a href="the-multinomial-logit-model.html#cb21-5" aria-hidden="true" tabindex="-1"></a> <span class="st">&quot;Constant &quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;-1.1&quot;</span>,<span class="st">&quot;-1.1&quot;</span>,<span class="st">&quot;-1.1&quot;</span>),</span>
<span id="cb21-6"><a href="the-multinomial-logit-model.html#cb21-6" aria-hidden="true" tabindex="-1"></a> <span class="st">&quot;Income &quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;-0.008&quot;</span>, <span class="st">&quot;-0.008&quot;</span>, <span class="st">&quot;-0.008&quot;</span>),</span>
<span id="cb21-7"><a href="the-multinomial-logit-model.html#cb21-7" aria-hidden="true" tabindex="-1"></a> <span class="st">&quot;Constant  &quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;0.0&quot;</span>,<span class="st">&quot;-0.3&quot;</span>,<span class="st">&quot;-1.1&quot;</span>),</span>
<span id="cb21-8"><a href="the-multinomial-logit-model.html#cb21-8" aria-hidden="true" tabindex="-1"></a> <span class="st">&quot;Income  &quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;0.000&quot;</span>, <span class="st">&quot;-0.002&quot;</span>, <span class="st">&quot;-0.008&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb21-9"><a href="the-multinomial-logit-model.html#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">&quot;Changes in Alternative Specific Constants and Income Parameters&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-10"><a href="the-multinomial-logit-model.html#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span></span>
<span id="cb21-11"><a href="the-multinomial-logit-model.html#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&quot;TRansit as Base Alternative&quot;</span><span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot;Change in Parameters&quot;</span> <span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot;Drive Alone as Base Alternative&quot;</span> <span class="ot">=</span> <span class="dv">2</span>), <span class="at">align =</span> <span class="st">&quot;center&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:compareutilities">Table 4.7: </span>Changes in Alternative Specific Constants and Income Parameters
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
TRansit as Base Alternative
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Change in Parameters
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Drive Alone as Base Alternative
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Alternative
</th>
<th style="text-align:left;">
Constant
</th>
<th style="text-align:left;">
Income
</th>
<th style="text-align:left;">
Constant
</th>
<th style="text-align:left;">
Income
</th>
<th style="text-align:left;">
Constant
</th>
<th style="text-align:left;">
Income
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Drive Alone
</td>
<td style="text-align:left;">
1.1
</td>
<td style="text-align:left;">
0.008
</td>
<td style="text-align:left;">
-1.1
</td>
<td style="text-align:left;">
-0.008
</td>
<td style="text-align:left;">
0.0
</td>
<td style="text-align:left;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Shared Ride
</td>
<td style="text-align:left;">
0.8
</td>
<td style="text-align:left;">
0.006
</td>
<td style="text-align:left;">
-1.1
</td>
<td style="text-align:left;">
-0.008
</td>
<td style="text-align:left;">
-0.3
</td>
<td style="text-align:left;">
-0.002
</td>
</tr>
<tr>
<td style="text-align:left;">
Transit
</td>
<td style="text-align:left;">
0.0
</td>
<td style="text-align:left;">
0.000
</td>
<td style="text-align:left;">
-1.1
</td>
<td style="text-align:left;">
-0.008
</td>
<td style="text-align:left;">
-1.1
</td>
<td style="text-align:left;">
-0.008
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="IIA-section" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Independence of Irrelevant Alternatives Property</h2>
<p>One of the most widely discussed aspects of the multinomial logit model is its
independence from irrelevant alternatives (IIA) property. The IIA property
states that for any individual, the ratio of the probabilities of choosing two
alternatives is independent of the presence or attributes of any other
alternative. The premise is that other alternatives are irrelevant to the
decision of choosing between the two alternatives in the pair. To illustrate
this, consider a multinomial logit model for the choice among three intercity
travel modes – automobile, rail, and bus. The probability of choosing
automobile, rail and bus are:</p>
<p><span class="math display" id="eq:probchooseauto">\[\begin{equation}
Pr(Auto) = \frac{\exp(V_{Auto})}{\exp(V_{Auto})+\exp(V_{Bus})+\exp(V_{Rail})}
\tag{4.36}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:probchoosebus">\[\begin{equation}
Pr(Bus) = \frac{\exp(V_{Bus})}{\exp(V_{Auto})+\exp(V_{Bus})+\exp(V_{Rail})}
\tag{4.37}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:probchooserail">\[\begin{equation}
Pr(Rail) = \frac{\exp(V_{Rail})}{\exp(V_{Auto})+\exp(V_{Bus})+\exp(V_{Rail})}
\tag{4.38}
\end{equation}\]</span></p>
<p>The ratios of each pair of probabilities are:</p>
<p><span class="math display" id="eq:probratioab">\[\begin{equation}
\frac{Pr(Auto)}{Pr(Bus)} = \frac{\exp(V_{Auto})}{\exp(V_{Bus})} = \exp(V_{Auto} - V_{Bus})
\tag{4.39}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:probratioar">\[\begin{equation}
\frac{Pr(Auto)}{Pr(Rail)} = \frac{\exp(V_{Auto})}{\exp(V_{Rail})} = \exp(V_{Auto} - V_{Rail})
\tag{4.40}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:probratiobr">\[\begin{equation}
\frac{Pr(Bus)}{Pr(Rail)} = \frac{\exp(V_{Bus})}{\exp(V_{Rail})} = \exp(V_{Bus} - V_{Rail})
\tag{4.41}
\end{equation}\]</span></p>
<p>The ratios of probabilities for each pair of alternatives depend only on the
attributes of those alternatives and not on the attributes of the third
alternative and would remain the same regardless of whether that third
alternative is available or not. This formulation can be generalized to any
pair of alternatives by:</p>
<p><span class="math display" id="eq:probratioalts">\[\begin{equation}
\frac{Pr(i)}{Pr(k)} = \frac{\exp(V_i)}{\exp(V_k)} = \exp(V_i - V_k)
\tag{4.42}
\end{equation}\]</span></p>
<p>which, as before, is independent of the number or attributes of other alternatives in the choice set.</p>
<p>The IIA property has some important ramifications in the formulation, estimation
and use of multinomial logit models. The independence of irrelevant
alternatives property allows the addition or removal of an alternative from the
choice set without affecting the structure or parameters of the model. The
flexibility of applying the model to cases with different choice sets has a
number of advantages. First, the model can be estimated and applied in cases
where different members of the population (and sample) face different sets of
alternatives. For example, in the case of intercity mode choice, individuals
traveling between some city pairs may not have air service and/or rail service.
Second, this property simplifies the estimation of the parameters in the
multinomial logit model (as will be discussed later). Third, this property is
advantageous when applying a model to the prediction of choice probabilities for
a new alternative.</p>
<p>On the other hand, the IIA property may not properly reflect the behavioral
relationships among groups of alternatives. That is, other alternatives may not
be irrelevant to the ratio of probabilities between a pair of alternatives. In
some cases, this will result in erroneous predictions of choice probabilities.
An extreme example of this problem is the classic “red bus/blue bus paradox.”</p>
<div id="bus-paradox" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> The Red Bus/Blue Bus Paradox</h3>
<p>Consider the case of a commuter who has a choice of going to work by auto or
taking a blue bus. Assume that the attributes of the auto and the blue bus are
such that the probability of choosing auto is two-thirds and blue bus is
one-third so the ratio of their choice probabilities is 2:1. Now suppose that a
competing bus operator introduces red bus service (the bus is painted red,
rather than blue) on the same route, operating the same vehicle type, using the
same schedule and serving the same stops as the blue bus service. Thus, the
only difference between the red and blue bus services is the color of the buses.</p>
<p>The most reasonable expectation, in this case, is that the same share of people
will choose auto and bus and that the bus riders will split equally between the
red and blue bus services. That is, the addition of the red bus to the
commuters’ choice set should have no, or very little, effect on the share of
commuters choosing auto since this change does not affect the relative quality
of drive alone and bus. Therefore, we expect choice probabilities following the
initiation of red bus service to be auto, two-thirds; blue bus, one-sixth and
red bus, one-sixth. However, due to the IIA property, the multinomial logit
model will maintain the relative probability of auto and blue bus as 2:1. If we
assume that people are indifferent to color of their transit vehicle, the two
bus services will have the same representative utility and consequently, their
relative probabilities will be 1:1 and the share probabilities for the three
alternatives will be: Pr(Auto) = ½, Pr(Blue Bus) = 1/4, and Pr(Red Bus) = 1/4.
That is, the probability (share) of people choosing auto will decline from
two-thirds to one half as a result of introducing an alternative which is
identical to an existing alternative<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>. The red bus/blue bus
paradox provides an important illustration of the possible consequences of the
IIA property. Although this is an extreme case; the IIA property can be a
problem in other, less extreme cases.</p>
</div>
</div>
<div id="example-prediction-with-multinomial-logit-model" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Example: Prediction with Multinomial Logit Model</h2>
<p>We illustrate the application of multinomial logit models with different
specifications in the context of mode choice analysis. Consider a commute trip
by an individual who has three available modes in the choice set: drive alone,
carpool, and bus. The examples in this section illustrate the manner in which
different utility specifications and the estimated parameters associated with
them are used to predict choice probabilities based on characteristics of the
traveler (decision-maker) and attributes of the alternatives. These examples
progress from the simplest models to moderately complex models.</p>
<p><strong>Example 1 – Constants Only Model</strong></p>
<p>The simplest specification of the multinomial logit model is the ‘constants
only’ model, in which the utility of each alternative has a fixed value for all
decision-makers. Typically, the alternative specific constants are considered
to represent the average effect of all factors that influence the choice but are
not included in the utility specification. For example, factors such as
comfort, safety, privacy and reliability may be excluded due to the difficulty
associated with their measurement. In the constants only model, it is
implicitly assumed that the constants reflect the average effects of all the
variables affecting the choice decision, since no variables are included
explicitly in the utility specification. If these constants are 0.0, -1.6 and
-1.8 for drive alone, shared ride and transit, respectively, the probability
calculation is as shown in Table <a href="the-multinomial-logit-model.html#tab:constants">4.8</a>.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:constants">Table 4.8: </span>MNL Properties for Constants Only Model
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Utility
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
Alternative
</th>
<th style="text-align:left;">
Expression
</th>
<th style="text-align:right;">
Value
</th>
<th style="text-align:right;">
Exponent
</th>
<th style="text-align:right;">
Probability
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Drive Alone
</td>
<td style="text-align:left;">
0.0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
0.7314243
</td>
</tr>
<tr>
<td style="text-align:left;">
Shared Ride
</td>
<td style="text-align:left;">
-1.60
</td>
<td style="text-align:right;">
-1.6
</td>
<td style="text-align:right;">
0.2018965
</td>
<td style="text-align:right;">
0.1476720
</td>
</tr>
<tr>
<td style="text-align:left;">
Transit
</td>
<td style="text-align:left;">
-1.80
</td>
<td style="text-align:right;">
-1.8
</td>
<td style="text-align:right;">
0.1652989
</td>
<td style="text-align:right;">
0.1209036
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
1.3671954
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
</tbody>
</table>
<p>As expected, Drive Alone has the highest probability, followed by Shared Ride, and TRansit.</p>
<p><strong>Example 2 – Including Mode Related Variables - Travel Time and Travel Cost</strong></p>
<p>Two key attributes that influence choice of mode are travel time and travel
cost. We include these variables in the deterministic component of the utility
function of each mode with the parameter for time (in minutes) equal to -0.045
and for cost (in cents) equal to -0.004 for all three modes, Table 4.9. This
implies that a minute of travel time (or a cent of cost) has the same marginal
disutility regardless of the mode; such variables are referred to as <em>generic</em>
variables. The negative signs of the travel time and travel cost coefficients
imply that the utility of a mode and the probability that it will be chosen
decreases as the travel time or travel cost of that mode increases. Positive
coefficients would be inconsistent with our understanding of travel behavior and
therefore any specification which results in a positive sign for travel time or
travel cost should be rejected. Such counter-intuitive results are most likely
due to an incorrect or inadequate model specification; however, it is possible
that the data from any particular sample leads to such counter-intuitive
results.</p>
<p>The inclusion of travel time and travel cost variables induces a change in the
alternative specific constants, to -1.865 for shared ride and -0.650 for
transit, as the effect of excluding these time and cost variables is removed
from the constants. Such changes in alternative specific constants, as a result
of the introduction of new variables or the elimination of included variables
preserve the sample shares<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a> and are expected.</p>
<p>To illustrate the application of the multinomial logit model for the above
utility equation, we assume travel time and travel cost values as follows:</p>
<table>
<thead>
<tr class="header">
<th align="left">Mode</th>
<th align="left">Travel Time</th>
<th align="left">Travel Cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Drive Alone</td>
<td align="left">25 minutes</td>
<td align="left">$1.75</td>
</tr>
<tr class="even">
<td align="left">Shared Ride</td>
<td align="left">28 minutes</td>
<td align="left">$0.75</td>
</tr>
<tr class="odd">
<td align="left">TRansit</td>
<td align="left">55 minutes</td>
<td align="left">$1.25</td>
</tr>
</tbody>
</table>
<p>The utilities and probabilities are calculated as shown in Table <a href="the-multinomial-logit-model.html#tab:utimecost">4.9</a>.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="the-multinomial-logit-model.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">utility_table</span>(</span>
<span id="cb22-2"><a href="the-multinomial-logit-model.html#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Drive Alone&quot;</span> <span class="ot">=</span> <span class="st">&quot;-0.045*25-0.004*175&quot;</span>,</span>
<span id="cb22-3"><a href="the-multinomial-logit-model.html#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Shared Ride&quot;</span> <span class="ot">=</span> <span class="st">&quot;-1.865-0.045*28-0.004*75&quot;</span>,</span>
<span id="cb22-4"><a href="the-multinomial-logit-model.html#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Transit&quot;</span> <span class="ot">=</span> <span class="st">&quot;-0.650-0.045*55-0.004*125&quot;</span>)</span>
<span id="cb22-5"><a href="the-multinomial-logit-model.html#cb22-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="the-multinomial-logit-model.html#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">&quot;MNL Probabilities for Time and Cost Model&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-7"><a href="the-multinomial-logit-model.html#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb22-8"><a href="the-multinomial-logit-model.html#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&quot;Utility&quot;</span><span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">2</span>), <span class="at">align =</span> <span class="st">&quot;center&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:utimecost">Table 4.9: </span>MNL Probabilities for Time and Cost Model
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Utility
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
Alternative
</th>
<th style="text-align:left;">
Expression
</th>
<th style="text-align:right;">
Value
</th>
<th style="text-align:right;">
Exponent
</th>
<th style="text-align:right;">
Probability
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Drive Alone
</td>
<td style="text-align:left;">
-0.045<em>25-0.004</em>175
</td>
<td style="text-align:right;">
-1.825
</td>
<td style="text-align:right;">
0.1612176
</td>
<td style="text-align:right;">
0.7314243
</td>
</tr>
<tr>
<td style="text-align:left;">
Shared Ride
</td>
<td style="text-align:left;">
-1.865-0.045<em>28-0.004</em>75
</td>
<td style="text-align:right;">
-3.425
</td>
<td style="text-align:right;">
0.0325493
</td>
<td style="text-align:right;">
0.1476720
</td>
</tr>
<tr>
<td style="text-align:left;">
Transit
</td>
<td style="text-align:left;">
-0.650-0.045<em>55-0.004</em>125
</td>
<td style="text-align:right;">
-3.625
</td>
<td style="text-align:right;">
0.0266491
</td>
<td style="text-align:right;">
0.1209036
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.2204160
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
</tbody>
</table>
<p>This specification can be refined further by decomposing travel time into its
two major components: (1) in-vehicle travel time, and (2) out-of-vehicle travel
time. In-vehicle time (IVT) is defined as the time spent inside the vehicle,
and out-of-vehicle time (OVT) is the time not spent inside the vehicle
(including access time, waiting time, and egress time). There is an abundance
of empirical evidence that travelers are much more sensitive to out-of-vehicle
time than to in-vehicle time and therefore a minute of out-of-vehicle time will
generate a higher disutility than a minute of in-vehicle time. This will be
reflected in the modal utilities by a larger negative coefficient on
out-of-vehicle time than on in-vehicle time. Introduction of this refinement
will usually result in a less negative parameter for in vehicle time and a more
negative parameter for out of vehicle time than for total time; say -0.031 and
-0.062, respectively. If the travel times are split as follows:</p>
<table>
<thead>
<tr class="header">
<th align="left">Mode</th>
<th align="left">IVT</th>
<th align="left">OVT</th>
<th align="left">Travel Cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Drive Alone</td>
<td align="left">21 minutes</td>
<td align="left">4 minutes</td>
<td align="left">$1.75</td>
</tr>
<tr class="even">
<td align="left">Shared Ride</td>
<td align="left">23 minutes</td>
<td align="left">5 minutes</td>
<td align="left">$0.75</td>
</tr>
<tr class="odd">
<td align="left">Bus</td>
<td align="left">25 minutes</td>
<td align="left">30 minutes</td>
<td align="left">$1.25</td>
</tr>
</tbody>
</table>
<p>the new systematic utilities and choice probabilities are as computed in Table
<a href="the-multinomial-logit-model.html#tab:uivtovt">4.10</a>:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="the-multinomial-logit-model.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">utility_table</span>(</span>
<span id="cb23-2"><a href="the-multinomial-logit-model.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Drive Alone&quot;</span> <span class="ot">=</span> <span class="st">&quot;-0.031*21-0.062*4-0.004*175&quot;</span>,</span>
<span id="cb23-3"><a href="the-multinomial-logit-model.html#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Shared Ride&quot;</span> <span class="ot">=</span> <span class="st">&quot;-1.90-0.031*23-0.062*5-0.004*75&quot;</span>,</span>
<span id="cb23-4"><a href="the-multinomial-logit-model.html#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Transit&quot;</span> <span class="ot">=</span> <span class="st">&quot;-0.80-0.031*25-0.062*30-0.004*125&quot;</span>)</span>
<span id="cb23-5"><a href="the-multinomial-logit-model.html#cb23-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="the-multinomial-logit-model.html#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">&quot;MNL Probabilities for Time and Cost Model&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-7"><a href="the-multinomial-logit-model.html#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb23-8"><a href="the-multinomial-logit-model.html#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&quot;Utility&quot;</span><span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">2</span>), <span class="at">align =</span> <span class="st">&quot;center&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:uivtovt">Table 4.10: </span>MNL Probabilities for Time and Cost Model
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Utility
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
Alternative
</th>
<th style="text-align:left;">
Expression
</th>
<th style="text-align:right;">
Value
</th>
<th style="text-align:right;">
Exponent
</th>
<th style="text-align:right;">
Probability
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Drive Alone
</td>
<td style="text-align:left;">
-0.031<em>21-0.062</em>4-0.004*175
</td>
<td style="text-align:right;">
-1.599
</td>
<td style="text-align:right;">
0.2020985
</td>
<td style="text-align:right;">
0.7729036
</td>
</tr>
<tr>
<td style="text-align:left;">
Shared Ride
</td>
<td style="text-align:left;">
-1.90-0.031<em>23-0.062</em>5-0.004*75
</td>
<td style="text-align:right;">
-3.223
</td>
<td style="text-align:right;">
0.0398354
</td>
<td style="text-align:right;">
0.1523460
</td>
</tr>
<tr>
<td style="text-align:left;">
Transit
</td>
<td style="text-align:left;">
-0.80-0.031<em>25-0.062</em>30-0.004*125
</td>
<td style="text-align:right;">
-3.935
</td>
<td style="text-align:right;">
0.0195457
</td>
<td style="text-align:right;">
0.0747504
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.2614796
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
</tbody>
</table>
<p><strong>Example 3 – Including Decision-Maker Related Biases - Income</strong>
The preceding examples do not include any characteristics of the traveler in the
modal utilities. However, we know that choice probabilities of the available
modes also depend on characteristics of the traveler, such as his/her income.
Economic theory and empirical evidence suggests that higher income travelers are
less likely to choose transit than drive alone or carpool. We can incorporate
this behavior in the model by including an alternative specific income variable
in the utility of up to two of the alternatives; in this case, we include income
in the transit alternative with a negative coefficient. That is, everything
else held constant, the utility of transit decreases as the income of the
traveler increases. Consequently, a higher income traveler will have a lower
probability of choosing transit than a lower income traveler. The absence of an
alternative specific parameter for the carpool alternative implies that the
choice of carpool, relative to drive alone, is unaffected by a traveler’s
income. The alternative specific constant of the transit utility changes
substantially from the preceding example as it no longer reflects the average
effect of excluding income from the transit utility specification. The
calculation of utilities and probabilities for this model for a person from a
household with $50,000 annual income is shown in <a href="the-multinomial-logit-model.html#tab:uivtovtcost">4.11</a>.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="the-multinomial-logit-model.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">utility_table</span>(</span>
<span id="cb24-2"><a href="the-multinomial-logit-model.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Drive Alone&quot;</span> <span class="ot">=</span> <span class="st">&quot; -0.031*21-0.062*4-0.004*175&quot;</span>,</span>
<span id="cb24-3"><a href="the-multinomial-logit-model.html#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Shared Ride&quot;</span> <span class="ot">=</span> <span class="st">&quot;-1.90-0.031*23-0.062*5-0.004*75&quot;</span>,</span>
<span id="cb24-4"><a href="the-multinomial-logit-model.html#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Transit&quot;</span> <span class="ot">=</span> <span class="st">&quot;-0.50-0.031*25-0.062*30-0.004*125-0.0087*50&quot;</span>)</span>
<span id="cb24-5"><a href="the-multinomial-logit-model.html#cb24-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="the-multinomial-logit-model.html#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">&quot;MNL Probabilities for In and Out of Vehicle Time, Cost and Income Model&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-7"><a href="the-multinomial-logit-model.html#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb24-8"><a href="the-multinomial-logit-model.html#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&quot;Utility&quot;</span><span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">2</span>), <span class="at">align =</span> <span class="st">&quot;center&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:uivtovtcost">Table 4.11: </span>MNL Probabilities for In and Out of Vehicle Time, Cost and Income Model
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Utility
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
Alternative
</th>
<th style="text-align:left;">
Expression
</th>
<th style="text-align:right;">
Value
</th>
<th style="text-align:right;">
Exponent
</th>
<th style="text-align:right;">
Probability
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Drive Alone
</td>
<td style="text-align:left;">
-0.031<em>21-0.062</em>4-0.004*175
</td>
<td style="text-align:right;">
-1.599
</td>
<td style="text-align:right;">
0.2020985
</td>
<td style="text-align:right;">
0.7802692
</td>
</tr>
<tr>
<td style="text-align:left;">
Shared Ride
</td>
<td style="text-align:left;">
-1.90-0.031<em>23-0.062</em>5-0.004*75
</td>
<td style="text-align:right;">
-3.223
</td>
<td style="text-align:right;">
0.0398354
</td>
<td style="text-align:right;">
0.1537978
</td>
</tr>
<tr>
<td style="text-align:left;">
Transit
</td>
<td style="text-align:left;">
-0.50-0.031<em>25-0.062</em>30-0.004<em>125-0.0087</em>50
</td>
<td style="text-align:right;">
-4.070
</td>
<td style="text-align:right;">
0.0170774
</td>
<td style="text-align:right;">
0.0659330
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.2590113
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
</tbody>
</table>
<p>The probability of choosing transit is smaller for this traveler than would have
been predicted using the model reported in the preceding example. This model
will give decreasing transit probabilities for higher income travelers and
increasing transit probabilities for lower income travelers. That is, the lower
the traveler’s income, the greater his/her probability of choosing the least
expensive mode of travel (transit), an intuitive and reasonable result.</p>
<p><strong>Example 4 – Interaction of Mode Attributes and Decision-Maker Related Biases</strong></p>
<p>An alternative method of including income in the utility specification is to use
income as a deflator of cost by forming a variable by dividing cost by income.
This formulation reflects the rationale that cost becomes a less important
factor in the choice of a travel mode as the income of the traveler increases.
The revised utility functions and calculations are shown in Table <a href="the-multinomial-logit-model.html#tab:uinteraction">4.12</a>
using the values for the modal attributes and income as used in preceding
example.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="the-multinomial-logit-model.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">utility_table</span>(</span>
<span id="cb25-2"><a href="the-multinomial-logit-model.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">&quot;Drive Alone&quot;</span> <span class="ot">=</span> <span class="st">&quot; -0.031*21-0.062*4-0.153*(175/50) &quot;</span>,</span>
<span id="cb25-3"><a href="the-multinomial-logit-model.html#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Shared Ride&quot;</span> <span class="ot">=</span> <span class="st">&quot; -1.90-0.031*23-0.062*5-0.153*(75/50)   &quot;</span>,</span>
<span id="cb25-4"><a href="the-multinomial-logit-model.html#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;Transit&quot;</span> <span class="ot">=</span> <span class="st">&quot;-0.45-0.031*25-0.062*30-0.153*(125/50)&quot;</span>)</span>
<span id="cb25-5"><a href="the-multinomial-logit-model.html#cb25-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb25-6"><a href="the-multinomial-logit-model.html#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">caption =</span> <span class="st">&quot;MNL Probabilities for In and Out of Vehicle Time, Cost/Income Model&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-7"><a href="the-multinomial-logit-model.html#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb25-8"><a href="the-multinomial-logit-model.html#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">&quot;Utility&quot;</span><span class="ot">=</span> <span class="dv">2</span>, <span class="st">&quot; &quot;</span> <span class="ot">=</span> <span class="dv">2</span>), <span class="at">align =</span> <span class="st">&quot;center&quot;</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:uinteraction">Table 4.12: </span>MNL Probabilities for In and Out of Vehicle Time, Cost/Income Model
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Utility
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
Alternative
</th>
<th style="text-align:left;">
Expression
</th>
<th style="text-align:right;">
Value
</th>
<th style="text-align:right;">
Exponent
</th>
<th style="text-align:right;">
Probability
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Drive Alone
</td>
<td style="text-align:left;">
-0.031<em>21-0.062</em>4-0.153*(175/50)
</td>
<td style="text-align:right;">
-1.4345
</td>
<td style="text-align:right;">
0.2382345
</td>
<td style="text-align:right;">
0.7631451
</td>
</tr>
<tr>
<td style="text-align:left;">
Shared Ride
</td>
<td style="text-align:left;">
-1.90-0.031<em>23-0.062</em>5-0.153*(75/50)
</td>
<td style="text-align:right;">
-3.1525
</td>
<td style="text-align:right;">
0.0427451
</td>
<td style="text-align:right;">
0.1369270
</td>
</tr>
<tr>
<td style="text-align:left;">
Transit
</td>
<td style="text-align:left;">
-0.45-0.031<em>25-0.062</em>30-0.153*(125/50)
</td>
<td style="text-align:right;">
-3.4675
</td>
<td style="text-align:right;">
0.0311949
</td>
<td style="text-align:right;">
0.0999278
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.3121745
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
</tbody>
</table>
<p>This specification of income in the utility function also results in lower
income travelers predicted to have higher probability of choosing transit; it
also suggests that such travelers will increase their probability of choosing
carpool, the least expensive mode. The reader should compute the probabilities
for different income values and verify the response pattern.</p>
</div>
<div id="measures-of-response-to-changes-in-attributes-of-alternatives" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Measures of Response to Changes in Attributes of Alternatives</h2>
<p>Choice probabilities in logit models are a function of the values of the
attributes that define the utility of the alternatives; therefore, it is useful
to know the extent to which the probabilities change in response to changes in
the value of those attributes. For example, in a traveler’s mode choice
decision, an important question is to what extent the probability of choosing a
mode (rail, for example) will decrease/increase, if the fares of that mode are
increased by a certain amount. Similarly, a transit agency may want to know the
gain in ridership that is likely to occur in response to service improvements
(increased frequency). This section describes various aspects of understanding
and quantifying the response to changes in attributes of alternatives.</p>
<div id="derivatives-of-choice-probabilities" class="section level3" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Derivatives of Choice Probabilities</h3>
<p>One measure for evaluating the response to changes is to calculate the
<em>derivatives</em> of the choice probabilities of each alternative with respect to
the variable in question. Usually, one is concerned about the change in
probability of an alternative, <span class="math inline">\(P_i\)</span>, with respect to the change in attributes
of that alternative <span class="math inline">\(X_i\)</span>. This measure, the <em>direct derivative</em>, is computed
by differentiating <span class="math inline">\(P_i\)</span> with respect to <span class="math inline">\(X_{ik}\)</span>, the <span class="math inline">\(k^{th}\)</span> attribute of
alternative <span class="math inline">\(i\)</span>. The mathematical expression for the <em>direct derivative</em> of
<span class="math inline">\(P_i\)</span> with respect to <span class="math inline">\(X_{ik}\)</span> is:</p>
<p><span class="math display" id="eq:expressionfordirectderivative">\[\begin{equation}
\displaystyle \frac{\partial P_{i}}{\partial X_{ik}} = \displaystyle \frac{\partial V_{i}}{\partial X_{ik}} \times (P_{i}) \times (1-P_{i})  
\tag{4.43}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(V_i\)</span> is the utility of the alternative.<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a></p>
<p>Typically the utility function is specified to be linear in parameters; that is:</p>
<p><span class="math display" id="eq:linearutility">\[\begin{equation}
V_{i} = \beta_{0} + \beta_{1}X_{1i} + \beta_{2}X_{2i} + \cdots +  \beta_{k}X_{ki} + \cdots + \beta_{K}X_{Ki}  
\tag{4.44}
\end{equation}\]</span></p>
<p>In this case, the expression for the <em>direct derivative</em> of <span class="math inline">\(P_i\)</span> with respect to <span class="math inline">\(X_{ik}\)</span> reduces to:</p>
<p><span class="math display" id="eq:reducesexpressionfordirectderivative">\[\begin{equation}
\displaystyle \frac{\partial P_{i}}{\partial X_{ki}} = \beta_{k} \times (P_{i}) \times (1-P_{i}) 
\tag{4.45}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\beta_{k}\)</span> is the coefficient of attribute <span class="math inline">\(k\)</span>.</p>
<p>The value of the derivative is largest at <span class="math inline">\(P_{i} = \frac{1}{2}\)</span> and becomes smaller as <span class="math inline">\(P_{i}\)</span> approaches zero or one. This implies that the magnitude of the response to a change in an attribute will be greatest when the choice probability for the alternative under consideration is 0.5 and this response diminishes as the probability approaches zero or one. The direct derivative is simply the slope of the logit model probability curve illustrated in Figure 4.4 and that its mathematical properties are consistent with the qualitative discussion of the S-shape of the logit probability curve in section 4.1.1. The sign of the derivative is the same as the sign of the parameter describing the impact of <span class="math inline">\(X_{ik}\)</span> in the utility of alternative <span class="math inline">\(i\)</span>. Thus, an increase in <span class="math inline">\(X_{ik}\)</span> will increase (decrease) <span class="math inline">\(P_{i}\)</span> if <span class="math inline">\(\beta_{ik}\)</span> is positive (negative).</p>
<p>Often it is important to understand how the choice probability of other alternatives changes in response to a given change in the attribute level of the action alternative. This measure, termed the <span class="math inline">\(cross\)</span> <span class="math inline">\(derivative\)</span>, is obtained by computing the derivative of the choice probability of an alternative,<span class="math inline">\(P_{j}\)</span> , with respect to the attribute of the changed alternative, <span class="math inline">\(X_{ik}\)</span>. This <span class="math inline">\(cross\)</span> <span class="math inline">\(derivative\)</span> for linear utility functions is:<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a></p>
<p><span class="math display" id="eq:fortyfive">\[\begin{equation}
\displaystyle \frac{\partial P_{i}}{\partial X_{ki}} = \beta_{k} \times (P_{i}) \times (1-P_{j})  
\tag{4.46}
\end{equation}\]</span></p>
<p>Often it is important to understand how the choice probability of other
alternatives changes in response to a given change in the attribute level of the
action alternative. This measure, termed the <em>cross derivative</em>, is obtained by
computing the derivative of the choice probability of an alternative, <span class="math inline">\(P_j\)</span>,
with respect to the attribute of the changed alternative, <span class="math inline">\(X_{ik}\)</span>. This <em>cross
derivative</em> for linear utility functions is:</p>
<p><span class="math display" id="eq:linearutilityforcrossderivative">\[\begin{equation}
\displaystyle \frac{\partial P_{j}}{\partial X_{ik}} = \beta_{k} \times (P_{i}) \times (P_{j})   \forall_{i} \ne j  
\tag{4.47}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\beta_{jk}\)</span> is the coefficient of the <span class="math inline">\(k^{th}\)</span> attribute of alternative <span class="math inline">\(j\)</span>,
<span class="math inline">\(P_{i}\)</span> is the probability of alternative <span class="math inline">\(i\)</span>, and
<span class="math inline">\(P_{j}\)</span> is the probability of alternative <span class="math inline">\(j\)</span>.</p>
<p>In this case, the sign of the derivative is opposite to the sign of the parameter describing the impact of <span class="math inline">\(X_{ik}\)</span> on the utility of alternative <span class="math inline">\(i\)</span>. Thus an increase in <span class="math inline">\(X_{ik}\)</span> will decrease (increase) the probability of choosing alternative, <span class="math inline">\(P_{i}\)</span>, if the parameter <span class="math inline">\(\beta_{k}\)</span> is positive (negative).</p>
<p>In this case, the sign of the derivative is opposite to the sign of the
parameter describing the impact of <span class="math inline">\(X_{ik}\)</span> on the utility of alternative <span class="math inline">\(i\)</span>.
Thus an increase in <span class="math inline">\(X_{ik}\)</span> will decrease (increase) the probability of
choosing alternative, <span class="math inline">\(P_j\)</span>, if the parameter <span class="math inline">\(\beta_k\)</span> is positive (negative).</p>
<p>It is useful to recognize that the sum of the derivatives over all the
alternatives must be equal to zero. That is,</p>
<p><span class="math display" id="eq:sumofderivativesequaltozero">\[\begin{align}
 \sum_{\forall_{j}}\frac{\partial P_{j}}{\partial X_{ik}}&amp;= 
  \frac{\partial P_{j}}{\partial X_{ik}} + \sum_{\forall_{j \ne i}}\frac{\partial P_{j}}{\partial X_{ik}}\\
&amp;= \beta_{k}P_{i}(1-P_{i}) - \sum_{\forall_{j \ne i}}\beta_{k}P_{i}P_{j}\\
&amp;= \beta_{k}P_{i}(1-P_{i}) - \beta_{k}P_{i}\sum_{\forall_{j \ne i}}P_{j}\\
&amp;= \beta_{k}P_{i}(1-P_{i}) - \beta_{k}P_{i}(1-P_{i})\\
&amp;= 0
\tag{4.48}
\end{align}\]</span></p>
<p>This is as expected. Since the sum of all probabilities is fixed at one, the
sum of the derivatives of the probability due to a change in any attribute of
any alternative must be equal to zero.</p>
</div>
<div id="elasticities-of-choice-probabilities" class="section level3" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> Elasticities of Choice Probabilities</h3>
<p>Elasticity is another measure that is used to quantify the extent to which the
choice probabilities of each alternative will change in response to the changes
in the value of an attribute. In general, elasticity is defined as the
percentage change in the response variable with respect to a one percent change
in an explanatory variable. In the context of logit models, the response
variable is the choice probability of an alternative, such as <span class="math inline">\(P_i\)</span>, and the
explanatory variable is the attribute <span class="math inline">\(X_{ik}\)</span>. Elasticities are different from
derivatives in that elasticities are normalized by the variable units. To
clearly illustrate the concept of elasticity, let us consider that <span class="math inline">\(P_{i1}\)</span> and
<span class="math inline">\(P_{i2}\)</span> are choice probabilities of an alternative <span class="math inline">\(i\)</span> at attribute levels
<span class="math inline">\(X_{i1}\)</span> and <span class="math inline">\(X_{i2}\)</span>, respectively. In this case, the elasticity is the
proportional change in the probability divided by the proportional change in the
attribute under consideration:</p>
<p><span class="math display" id="eq:Elasticity">\[\begin{equation}
\text{Elasticity} = \frac{\text{Pct Change in Probability}}{\text{Pct Change in Variable}}
= \frac{(P_{2}-P_{1})/P_{1}}{(X_{2}-X_{1})/X_{1}} = \frac{\Delta P/P_{1}}{\Delta X/X_{1}}
\tag{4.49}
\end{equation}\]</span></p>
<p>There is some ambiguity in the computation of this elasticity measure in terms of whether it should be normalized using the original probability-attribute combination (<span class="math inline">\(P_{i1}\)</span>, <span class="math inline">\(X_{i1}\)</span> ) or the new probability-attribute combination (<span class="math inline">\(P_{i2}\)</span>, <span class="math inline">\(X_{i2}\)</span>). A compromise approach is to compute the elasticity relative to the mid-point of both sets of variables, yielding a measure called the arc elasticity. The expression for arc elasticity is:</p>
<p>There is some ambiguity in the computation of this elasticity measure in terms
of whether it should be normalized using the original probability-attribute
combination (<span class="math inline">\(P_{i1}\)</span>, <span class="math inline">\(X_{i1}\)</span>) or the new probability-attribute combination
(<span class="math inline">\(P_{i2}\)</span>, <span class="math inline">\(X_{i2}\)</span>). A compromise approach is to compute the elasticity
relative to the mid-point of both sets of variables, yielding a measure called
the <em>arc elasticity</em>. The expression for arc elasticity is:
<span class="math display" id="eq:ArcElasticity">\[\begin{equation}
\displaystyle Arc Elasticity = \frac{\Bigg(\frac{(P_{2}-P_{1})}{(P_{1}+P_{2})/2)}\Bigg)}{\Bigg(\frac{(X_{2}-X_{1})}{(X_{1}+X_{2})/2)}\Bigg)} = \frac{\Bigg(\frac{(\Delta P)}{(P_{1}+P_{2})/2)}\Bigg)}{\Bigg(\frac{(\Delta X)}{(X_{1}+X_{2})/2)}\Bigg)}
\tag{4.50}
\end{equation}\]</span></p>
<p>Estimates of elasticity will differ depending on whether the normalization is at the start value, final value or mid-point values. This confusion can be avoided by computing elasticities for <span class="math inline">\(\underline{very\ small}\)</span> changes. When the elasticity is computed for infinitesimally small changes, the elasticity obtained is termed the point elasticity. The expression for point elasticity is given as a function of the derivatives discussed earlier (section 4.4.1):</p>
<p><span class="math display" id="eq:PointElasticity">\[\begin{equation}
\displaystyle \eta_{X}^{P} = \frac{\Bigg(\frac{\partial P}{P}\Bigg)}{\Bigg(\frac{\partial X}{X}\Bigg)} = \Bigg(\frac{\partial P}{\partial X}\Bigg) \times \Bigg(\frac{X}{P}\Bigg)
\tag{4.51}
\end{equation}\]</span></p>
<p>Estimates of elasticity will differ depending on whether the normalization is at
the start value, final value or mid-point values. This confusion can be avoided
by computing elasticities for <strong>very small</strong> changes. When the elasticity is
computed for infinitesimally small changes, the elasticity obtained is termed
the <em>point elasticity</em>. The expression for point elasticity is given as a
function of the derivatives discussed earlier (section 4.4.1):</p>
<p><span class="math display" id="eq:LevelPointElasticity">\[\begin{equation}
\displaystyle \eta_{X_{ik}}^{P_{i}} = \frac{\Bigg(\frac{\partial P_{i}}{P}\Bigg)}{\Bigg(\frac{\partial X_{ik}}{X_{ik}}\Bigg)} = \Bigg(\frac{\partial P_{i}}{\partial X_{ik}}\Bigg) \times \Bigg(\frac{X_{ik}}{P_{i}}\Bigg)
\tag{4.52}
\end{equation}\]</span></p>
<p>We are interested in both <em>direct-</em> and <em>cross-elasticities</em> corresponding to
the direct- and cross-derivatives discussed above. The direct elasticity
measures the percent change in the choice probability of alternative, <span class="math inline">\(P_i\)</span> with
respect to a percent change in the attribute level (<span class="math inline">\(X_{ik}\)</span>) of that
alternative:</p>
<p>We can substitute equation 4.45 into 4.51 to obtain the following expression for
the direct elasticity</p>
<p><span class="math display" id="eq:LevelPointDirectElasticity">\[\begin{equation}
\displaystyle \eta_{X_{ik}}^{P_{i}} = \beta_{k}P_{i}(1-P_{i})\Bigg(\frac{X_{ik}}{P_{i}}\Bigg) = \beta_{k}X_{ik}(1-P_{i})
\tag{4.53}
\end{equation}\]</span></p>
<p>Thus, the direct elasticity is not only a function of the parameter value, <span class="math inline">\(\beta_{k}\)</span>, for the attribute in the utility, but is also a function of the attribute level, <span class="math inline">\(X_{ik}\)</span>, at which the elasticity is being computed.</p>
<p>Thus, the direct elasticity is not only a function of the parameter value,
<span class="math inline">\(\beta_k\)</span>, for the attribute in the utility, but is also a function of the
attribute level, <span class="math inline">\(X_{ik}\)</span>, at which the elasticity is being computed.</p>
<p>Similarly, the cross-elasticity is defined as the proportional change in the
choice probability of an alternative (<span class="math inline">\(P_j\)</span>) with respect to a proportional
change in some attribute of another alternative (<span class="math inline">\(X_{ik}\)</span>). The expression for
cross elasticity in a multinomial logit model is given by:
<span class="math display" id="eq:LevelCrossElasticity">\[\begin{equation}
\displaystyle \eta_{X_{ik}}^{P_{j}} = \frac{\Bigg(\frac{\partial P_{j}}{P_{j}}\Bigg)}{\Bigg(\frac{\partial X_{ik}}{X_{ik}}\Bigg)} = \Bigg(\frac{\partial P_{j}}{\partial X_{ik}}\Bigg) \times \Bigg(\frac{X_{ik}}{P_{j}}\Bigg) \ \forall j\ne i
\tag{4.54}
\end{equation}\]</span></p>
<p>We substitute equation 4.46 into 4.53 to obtain the following expression for
cross elasticity of logit model probabilities:</p>
<p><span class="math display" id="eq:LevelPointCrossElasticity">\[\begin{equation}
\displaystyle \eta_{X_{ik}}^{P_{i}} = (-\beta_{k}P_{i}P_{j})\Bigg(\frac{X_{ik}}{P_{j}}\Bigg) = -\beta_{k}X_{ik}P_{i}
\tag{4.55}
\end{equation}\]</span></p>
<p>An important property of MNL models is that the cross-elasticities are the same
for all the other alternatives in the choice set. This property of the
multinomial logit model is another manifestation of the IIA property discussed
in the previous section.</p>
<p>The elasticity expressions derived above are based on the assumption that the
independent variables for which the elasticities are being derived are
continuous variables (<em>e.g.</em>, travel time and travel cost). However, if the
variable of interest is discrete in nature (<em>e.g.</em>, number of automobiles in a
household), it is not differentiable by definition. For this reason,
derivatives can not be derived for ordinal or categorical variables. An
alternative is to calculate the incremental change is each probability with
respect to a one unit change in an ordered variable or a category shift for
categorical variables and to use the differences to compute arc elasticities.</p>
</div>
</div>
<div id="measures-of-responses-to-changes-in-decision-maker-characteristics" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Measures of Responses to Changes in Decision Maker Characteristics</h2>
<p>Choice probabilities in logit models are also a function of the values of the
characteristics of the decision maker (traveler). Therefore, it is equally
useful to know the extent to which the probabilities of alternatives change in
response to changes in the value of these characteristics. For example, in a
traveler’s mode choice decision, an important question is to what extent the
probability of choosing a mode will decrease/increase, if the income of the
traveler changes by a certain amount. This section formulates both the
derivatives and elasticity equations for evaluating such responses and thereby
provides understanding and quantifies the response to changes in the
characteristics of travelers.</p>
<div id="derivatives-of-choice-probabilities-1" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Derivatives of Choice Probabilities</h3>
<p>Derivatives indicate the change in probability of each alternative in the choice
set per unit change in a characteristic of the traveler. The analysis approach
is similar to that employed in section 4.4. The important difference is that in
section 4.4, we were assessing the impact of a change in probability of an
alternative in response to a change in an attribute of a single alternative;
either the same alternative (direct-derivative and direct-elasticity) or another
alternative (cross-derivative and cross-elasticity). In the case of traveler
characteristics, those characteristics may appear in alternative specific form
in all alternatives (except for one reference alternative). Thus, we are
considering what, in effect, becomes a combination of one direct response and
multiple cross responses. Consider, for example, the probability of choosing
alternative <span class="math inline">\(i\)</span> in response to a change in income, specific to alternative <span class="math inline">\(i\)</span>.
That is,</p>
<p><span class="math display" id="eq:probichangeincomei">\[\begin{equation}
\frac{\partial P_i}{\partial Inc_i} = (1 - P_i)P_i\beta_{Inc_i}
\tag{4.56}
\end{equation}\]</span></p>
<p>However, since an identical change in income will occur for all alternatives in
which income appears as an alternative specific variable, we consider the
cross-derivative of the probability of choosing alternative <span class="math inline">\(i\)</span> in response to a
change in income, specific to alternative <span class="math inline">\(j\)</span>. That is,</p>
<p><span class="math display" id="eq:probichangeincomej">\[\begin{equation}
\frac{\partial P_i}{\partial Inc_j} = -P_iP_j\beta_{Inc,_j}
\tag{4.57}
\end{equation}\]</span></p>
<p>The corresponding sum over all alternatives <span class="math inline">\(i \ne j\)</span> is</p>
<p><span class="math display" id="eq:sumprobsalljnoti">\[\begin{equation}
\sum_{j\ne i}\frac{\partial P_i}{\partial Inc_j} = -P_i\sum_{j \ne i}P_j\beta_{Inc,_j}
\tag{4.58}
\end{equation}\]</span></p>
<p>and the sum over all alternatives including <span class="math inline">\(i\)</span> is</p>
<p><span class="math display" id="eq:sumprobsallj">\[\begin{equation}
\begin{split}
\frac{\partial P_i}{\partial Inc} = P_i(1-P_i)\beta_{Inc,_i}-\sum_{j\ne i}P_iP_j\beta_{Inc,_j}\\
= P_i\beta_{Inc,_j} - \sum_{\forall j}P_iP_j\beta_{Inc,_j}\\
= P_i[\beta_{Inc,_i} - \sum_{\forall j}P_j\beta_{Inc,_j}]\\
= P_i[\beta_{Inc,_i} - \overline{\beta}_{Inc}]\\
\end{split}
\tag{4.59}
\end{equation}\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(\overline{\beta}_{Inc}\)</span> is the probability weighted average of the
alternative specific income parameters</li>
</ul>
<p>That is, the derivative of the probability with respect to a change in income is
equal to the probability times the amount by which the income coefficient for
that alternative exceeds the probability weighted average income coefficient
over all alternatives<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a>.</p>
<p>It should be apparent that the sum over all alternatives of the income
derivatives must be equal to one to ensure that the total probability over all
alternatives is unchanged by any change in income. This can be shown by summing
equation 4.58 over all alternatives in the choice set.</p>
</div>
<div id="elasticities-of-choice-probabilities-1" class="section level3" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Elasticities of Choice Probabilities</h3>
<p>Elasticity is another measure that can be used to quantify the extent to which
the choice probabilities are influenced by changes in a variable; in this case,
a variable that describes the characteristics of the traveler. In this case,
the elasticity of the probability of alternative <span class="math inline">\(i\)</span> to a change in income is
given by</p>
<p><span class="math display" id="eq:elasticityitochangeinc">\[\begin{equation}
\eta_{Inc}^{P_i} = (\beta_{Inc_i} - \overline{\beta}_{Inc}) \times Inc
\tag{4.60}
\end{equation}\]</span></p>
<p>As before, the elasticity represents the proportional change in probability of an alternative to a proportional change in the explanatory variable.</p>
</div>
</div>
<div id="model-estimation-concept-and-method" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Model Estimation: Concept and Method</h2>
<p>Logit model development consists of formulating model specifications and
estimating numerical values of the parameters for the various attributes
specified in each utility function by fitting the models to the observed choice
data. The critical elements of this process become the selection of a preferred
specification based on statistical measures and judgment. Under some
circumstances, the model developer may impose constraints on the estimation to
ensure desired relationships with respect to the relative value of different
variables.</p>
<div id="graphical-representation-of-model-estimation" class="section level3" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Graphical Representation of Model Estimation</h3>
<p>We illustrate the basic concepts of model estimation using a binary choice model
with two variables and no constant. Consider that the only two modes available
to a traveler are auto and bus and the deterministic component of the utility
function for the two modes is defined as follows:</p>
<p><span class="math display" id="eq:sixty">\[\begin{equation}
  V_{Auto} = \beta_1 \times TravelTime_{Auto} +  \beta_{2} \times TravelCost_{Auto}
\tag{4.61}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:sixtyone">\[\begin{equation}
  V_{Bus} = \beta_1 \times TravelTime_{Bus} +  \beta_{2} \times TravelCost_{Bus}
\tag{4.62}
\end{equation}\]</span></p>
<p>Let us assume that in this example, bus has higher travel time and lower cost
than car. For a traveler, the choice of travel mode will depend on his/her
relative valuation of travel time and travel cost. A traveler who values time
much more than cost will have a higher utility for car; whereas, a traveler who
values time less than cost will have a higher utility for bus. This concept is
illustrated in Figure 4.5 which shows the time and cost values for auto and bus
iso-utility line<a href="#fn10" class="footnote-ref" id="fnref10"><sup>10</sup></a> for both types of travelers. When the
iso-utility lines are steep enough to ensure that some iso-utility line is below
bus and above car (case 1) implying a low value of time, bus will be the chosen
mode. Conversely, if the iso-utility lines are flat enough to ensure that some
iso-utility line is below car and above bus (case 2) implying a high value of
time, car will be the chosen mode.</p>
<p>The concept of iso-utility lines can be used to graphically describe the
estimation of model parameters using observed choice data. This is illustrated
in Figure 4.6 which shows the observed choice data for two travelers where each
traveler has a choice between bus and car. The first traveler chooses bus (Bus
1) whereas the second traveler chooses car (Car 2). The objective is to find an
iso-utility line with a slope that is steep enough to place Bus 1 above Car 1
and flat enough to place Bus 2 below Car 2. The figure shows that there many
iso-utility lines with different slopes that satisfy the above conditions.
However, even with only two observations, the range of the slopes of these lines
is limited. The addition of more choice observation will further reduce the
possible range of iso-utility lines. If all choosers are governed by the strict
utility equations 4.60 and 4.61; additional observations will narrow the range
of results to any satisfactory level of precision.</p>
<p>However, as discussed previously, we expect that the analyst will not know all
the variables that influence the traveler’s choice and/or will measure some
variables differently than the user. Thus, it is unlikely that the observations
can be separated by a single boundary. In this case, it becomes necessary to
use an estimation method which scores different estimation results in terms of
how well they identify the chosen alternatives. This is accomplished by using
maximum likelihood estimation methods. The maximum likelihood method consists
of finding model parameters which maximize the likelihood (posterior
probability) of the observed choices conditional on the model. That is, to
maximize the likelihood that the sample was generated from the model with the
selected parameter values.</p>
</div>
<div id="maximum-likelihood-estimation-theory" class="section level3" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> Maximum Likelihood Estimation Theory</h3>
<p>The procedure for maximum likelihood estimation involves two important steps: 1)
developing a joint probability density function of the observed sample, called
the <em>likelihood function</em>, and 2) estimating parameter values which maximize the
likelihood function. The likelihood function for a sample of ‘<em>T</em>’ individuals,
each with ‘<em>J</em>’ alternatives is defined as follows:</p>
<p><span class="math display" id="eq:sixtytwo">\[\begin{equation}
  L(\beta) = \prod_{\forall t \in T} \prod_{\forall j \in J}(P_{jt}(\beta))^{\delta_{jt}}
\tag{4.63}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\delta_{jt} = 1\)</span> is chosen indicator (<span class="math inline">\(=1\)</span>if <span class="math inline">\(j\)</span> is chosen by individual
<span class="math inline">\(t\)</span> and 0, otherwise) and <span class="math inline">\(P_{jt}\)</span> is the probability that individual <span class="math inline">\(t\)</span>
chooses alternative <span class="math inline">\(j\)</span>.</p>
<p>The values of the parameters which maximize the likelihood function are obtained
by finding the first derivative of the likelihood function and equating it to
zero. Since the log of a function yields the same maximum as the function and
is more convenient to differentiate, we maximize the <em>log-likelihood function</em>
instead of the likelihood function itself. The expressions for the log
likelihood function and its first derivative are shown in equations <a href="the-multinomial-logit-model.html#eq:sixtythree">(4.64)</a> and
<a href="the-multinomial-logit-model.html#eq:sixtyfour">(4.65)</a> respectively:</p>
<p><span class="math display" id="eq:sixtythree">\[\begin{equation}
  LL(\beta) = Log(L(\beta)) = \sum_{\forall t \in T} \sum_{\forall j \in J} \delta_{jt} \times ln(P_{jt}(\beta))
\tag{4.64}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:sixtyfour">\[\begin{equation}
\frac{\partial (LL)}{\partial \beta_k} = \sum_{\forall t \in T} \sum_{\forall j \in J} \delta_{jt} \times \frac{1}{P_{jt}} \times \frac{\partial P_{jt}(\beta)}{\partial \beta} \qquad \forall k
\tag{4.65}
\end{equation}\]</span><a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a></p>
<p>Further development of the derivative requires representation of the probability
function, <span class="math inline">\(P_{jt}\)</span>, expanded from the version that appears in Equation 4.5 is</p>
<p><span class="math display" id="eq:pjtexpansion">\[\begin{equation}
P_{jt}= \frac{\exp({X&#39;}_{jt}\beta)}{\sum_{j&#39;}\exp({X&#39;}_{jt}\beta)}
\tag{4.66}
\end{equation}\]</span></p>
<p>and the first derivative with respect to each element of <span class="math inline">\(\beta\)</span> is</p>
<p><span class="math display" id="eq:deriv1beta">\[\begin{equation}
\frac{\partial P_{jt}}{\partial \beta_k} = P_{jt}\left({X&#39;}_{jkt}-\sum_{j&#39;}P_{j&#39;t}X_{j&#39;kt}\right)   \forall k  
\tag{4.67}
\end{equation}\]</span><a href="#fn12" class="footnote-ref" id="fnref12"><sup>12</sup></a></p>
<p>Substituting Equation <a href="the-multinomial-logit-model.html#eq:deriv1beta">(4.67)</a> into Equation 4.64 gives</p>
<p><span class="math display" id="eq:dLLdBetak2">\[\begin{equation}
\frac{\partial (LL)}{\partial \beta_k} = \sum_{\forall t \in T} \sum_{\forall j \in J} \delta_{jt} \left({X&#39;}_{jt} - \sum_{j&#39;t} P_{j&#39;t}X_{j&#39;t} \right) \\
= \sum_{\forall t \in T} \sum_{\forall j \in J} (\delta_{jt} - P_{j&#39;t}) {X&#39;}_{jt}   \forall k
\tag{4.68}
\end{equation}\]</span></p>
<p>for the derivative of the log-likelihood with respect to <span class="math inline">\(\beta_k\)</span>. The maximum
likelihood is obtained by setting Equation <a href="the-multinomial-logit-model.html#eq:dLLdBetak2">(4.68)</a> equal to zero
and solving for the best values of the parameter vector, <span class="math inline">\(\hat{\beta}\)</span>. We can
be sure this is the solution for a maximum value provided that the second
derivative is negative definite. In this case, the second derivative of the
log-likelihood with respect to <span class="math inline">\(\beta\)</span> is</p>
<p><span class="math display" id="eq:d2LLdBeta">\[\begin{equation}
\frac{\partial^2 (LL)}{\partial \beta \partial \beta&#39;} = \sum_{\forall t \in T} \sum_{\forall j \in J} - P_{j&#39;t}({X&#39;}_{jt}-\overline{X}_t)({X&#39;}_{jt}-\overline{X}_t)&#39;
\tag{4.69}
\end{equation}\]</span></p>
<p>is negative definite for all values of <span class="math inline">\(\beta\)</span>. Equations <a href="the-multinomial-logit-model.html#eq:dLLdBetak2">(4.68)</a>
and <a href="the-multinomial-logit-model.html#eq:d2LLdBeta">(4.69)</a> are used to solve the maximum likelihood problem using a
variety of available algorithms. In most practical problems, this involves
significant computations and specialized computer programs to find the desired
solution.</p>
<p>The following example illustrates the application of maximum likelihood to
estimate logit model parameters.</p>
</div>
<div id="example-of-maximum-likelihood-estimation" class="section level3" number="4.6.3">
<h3><span class="header-section-number">4.6.3</span> Example of Maximum Likelihood Estimation</h3>
<p>Suppose a logit model of binary choice between car and bus is to be estimated.
For simplicity, let us assume the utility specification includes only the travel
time variable and that the deterministic portion of the utility function for the
two modes is defined as follows:</p>
<p><span class="math display" id="eq:Automodes">\[\begin{equation}
$\displaystyle V_{Auto} = \beta_{1} \times Travel \ Time_{Auto}$
\tag{4.70}
\end{equation}\]</span>
<span class="math display" id="eq:Busmodes">\[\begin{equation}
$\displaystyle V_{Bus} = \beta_{1} \times Travel \ Time_{Bus}$
\tag{4.71}
\end{equation}\]</span></p>
<p>Suppose that the estimation sample consists of observations of mode choice of
only three individuals. The modal travel times and observed choice for each of
the three individuals in the sample is as follows:</p>
<table>
<thead>
<tr class="header">
<th align="center">Individual #</th>
<th align="center">Auto Travel Time</th>
<th align="center">Bus Travel Time</th>
<th align="center">Chosen Mode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">30 minutes</td>
<td align="center">50 minutes</td>
<td align="center">Car (mode 1)</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">20 minutes</td>
<td align="center">10 minutes</td>
<td align="center">Car (mode 2)</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">40 minutes</td>
<td align="center">30 minutes</td>
<td align="center">Bus (mode 2)</td>
</tr>
</tbody>
</table>
<p>According to the logit model, the probabilities for the observed mode for each
individual are:</p>
<p><span class="math display" id="eq:IndividualP23" id="eq:IndividualP12" id="eq:IndividualP11">\[\begin{align}
\text{Individual}_1 \ (P_{11}) &amp;= 
  \frac{\exp(30\beta)}{\exp(50\beta)+\exp(30\beta)} = \frac{1}{1+\exp(20\beta)}   \tag{4.72}\\
\text{Individual}_2 (P_{12}) &amp;= 
  \frac{\exp(20\beta)}{\exp(10\beta)+\exp(20\beta)} = \frac{1}{1+\exp(-10\beta)} \tag{4.73}\\
\text{Individual}_3 \ (P_{23}) &amp;= 
  \frac{\exp(30\beta)}{\exp(30\beta)+\exp(40\beta)} = \frac{1}{1+\exp(10\beta)} \tag{4.74}
\end{align}\]</span></p>
<p>The log-likelihood expression for this sample will be as follows:</p>
<p><span class="math display" id="eq:LogLikelihood">\[\begin{align}
LL &amp;= \sum_{j=1,2}\sum_{t=1,2,3}\delta_{jt} \times \ln(P_{jt})\\
   &amp;= 1 \times \ln(P_{11}) + 0 \times \ln(P_{21}) + 1 \times \ln(P_{12}) \ldots \\
   &amp;= \ln(P_{11})+\ln(P_{12})+\ln(P_{23})\\
\tag{4.75}
\end{align}\]</span></p>
<p>A maximum likelihood estimator finds the value of the parameter <span class="math inline">\(\beta\)</span> which
maximizes the <em>log-likelihood</em> value. This solution is obtained by setting the
first derivative of the log-likelihood function equal to zero, and solving for
<span class="math inline">\(\hat{\beta}\)</span>. However, for this illustrative example, we can plot the graph
for log-likelihood (or likelihood) as a function of <span class="math inline">\(\beta\)</span> to find the point
where the maximum occurs. Figure <a href="the-multinomial-logit-model.html#fig:demo-likelihood">4.5</a> shows the graph of likelihood and
log-likelihood as a function of <span class="math inline">\(\beta\)</span>. It can be seen that the point where
the maximum occurs is identical for both the likelihood and the log-likelihood
functions, <em>i.e.</em>, at <span class="math inline">\(\beta = -0.076\)</span>. This value is called the maximum
likelihood estimate of <span class="math inline">\(\beta\)</span>.</p>
<p>Practical applications of logit models include multiple parameters and many
observations. Consequently, the maximum likelihood estimates for the parameters
cannot be found graphically. Specialized software packages are available for
this purpose.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="the-multinomial-logit-model.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate probabilities for example individuals</span></span>
<span id="cb26-2"><a href="the-multinomial-logit-model.html#cb26-2" aria-hidden="true" tabindex="-1"></a>demo_ps <span class="ot">&lt;-</span> <span class="cf">function</span>(beta){</span>
<span id="cb26-3"><a href="the-multinomial-logit-model.html#cb26-3" aria-hidden="true" tabindex="-1"></a>  v1a <span class="ot">&lt;-</span> beta <span class="sc">*</span> <span class="dv">30</span></span>
<span id="cb26-4"><a href="the-multinomial-logit-model.html#cb26-4" aria-hidden="true" tabindex="-1"></a>  v1t <span class="ot">&lt;-</span> beta <span class="sc">*</span> <span class="dv">50</span> </span>
<span id="cb26-5"><a href="the-multinomial-logit-model.html#cb26-5" aria-hidden="true" tabindex="-1"></a>  p1 <span class="ot">&lt;-</span> <span class="fu">exp</span>(v1a) <span class="sc">/</span> (<span class="fu">exp</span>(v1t) <span class="sc">+</span> <span class="fu">exp</span>(v1a)) </span>
<span id="cb26-6"><a href="the-multinomial-logit-model.html#cb26-6" aria-hidden="true" tabindex="-1"></a>  v2a <span class="ot">&lt;-</span> beta <span class="sc">*</span> <span class="dv">20</span></span>
<span id="cb26-7"><a href="the-multinomial-logit-model.html#cb26-7" aria-hidden="true" tabindex="-1"></a>  v2t <span class="ot">&lt;-</span> beta <span class="sc">*</span> <span class="dv">10</span></span>
<span id="cb26-8"><a href="the-multinomial-logit-model.html#cb26-8" aria-hidden="true" tabindex="-1"></a>  p2 <span class="ot">&lt;-</span> <span class="fu">exp</span>(v2a) <span class="sc">/</span> (<span class="fu">exp</span>(v2t) <span class="sc">+</span> <span class="fu">exp</span>(v2a)) </span>
<span id="cb26-9"><a href="the-multinomial-logit-model.html#cb26-9" aria-hidden="true" tabindex="-1"></a>  v3a <span class="ot">&lt;-</span> beta <span class="sc">*</span> <span class="dv">40</span></span>
<span id="cb26-10"><a href="the-multinomial-logit-model.html#cb26-10" aria-hidden="true" tabindex="-1"></a>  v3t <span class="ot">&lt;-</span> beta <span class="sc">*</span> <span class="dv">30</span></span>
<span id="cb26-11"><a href="the-multinomial-logit-model.html#cb26-11" aria-hidden="true" tabindex="-1"></a>  p3 <span class="ot">&lt;-</span> <span class="fu">exp</span>(v3t) <span class="sc">/</span> (<span class="fu">exp</span>(v3t) <span class="sc">+</span> <span class="fu">exp</span>(v3a)) </span>
<span id="cb26-12"><a href="the-multinomial-logit-model.html#cb26-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-13"><a href="the-multinomial-logit-model.html#cb26-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(p1, p2, p3)</span>
<span id="cb26-14"><a href="the-multinomial-logit-model.html#cb26-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-15"><a href="the-multinomial-logit-model.html#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="the-multinomial-logit-model.html#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate likelihood function</span></span>
<span id="cb26-17"><a href="the-multinomial-logit-model.html#cb26-17" aria-hidden="true" tabindex="-1"></a>demo_likelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(beta) {</span>
<span id="cb26-18"><a href="the-multinomial-logit-model.html#cb26-18" aria-hidden="true" tabindex="-1"></a>  ps <span class="ot">&lt;-</span> <span class="fu">demo_ps</span>(beta)</span>
<span id="cb26-19"><a href="the-multinomial-logit-model.html#cb26-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prod</span>(ps)</span>
<span id="cb26-20"><a href="the-multinomial-logit-model.html#cb26-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-21"><a href="the-multinomial-logit-model.html#cb26-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-22"><a href="the-multinomial-logit-model.html#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate log-likelihood</span></span>
<span id="cb26-23"><a href="the-multinomial-logit-model.html#cb26-23" aria-hidden="true" tabindex="-1"></a>demo_loglikelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(beta) {</span>
<span id="cb26-24"><a href="the-multinomial-logit-model.html#cb26-24" aria-hidden="true" tabindex="-1"></a>  ps <span class="ot">&lt;-</span> <span class="fu">demo_ps</span>(beta)</span>
<span id="cb26-25"><a href="the-multinomial-logit-model.html#cb26-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">log</span>(ps))</span>
<span id="cb26-26"><a href="the-multinomial-logit-model.html#cb26-26" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-27"><a href="the-multinomial-logit-model.html#cb26-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-28"><a href="the-multinomial-logit-model.html#cb26-28" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb26-29"><a href="the-multinomial-logit-model.html#cb26-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.2</span>, <span class="dv">0</span>, <span class="at">by =</span> <span class="fl">0.001</span>)</span>
<span id="cb26-30"><a href="the-multinomial-logit-model.html#cb26-30" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb26-31"><a href="the-multinomial-logit-model.html#cb26-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb26-32"><a href="the-multinomial-logit-model.html#cb26-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-33"><a href="the-multinomial-logit-model.html#cb26-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">Likelihood =</span> <span class="fu">demo_likelihood</span>(beta),</span>
<span id="cb26-34"><a href="the-multinomial-logit-model.html#cb26-34" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Log Likelihood</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">demo_loglikelihood</span>(beta)</span>
<span id="cb26-35"><a href="the-multinomial-logit-model.html#cb26-35" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb26-36"><a href="the-multinomial-logit-model.html#cb26-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(likelihood, value, <span class="sc">-</span>beta) <span class="sc">%&gt;%</span></span>
<span id="cb26-37"><a href="the-multinomial-logit-model.html#cb26-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> beta, <span class="at">y =</span> value)) <span class="sc">+</span> </span>
<span id="cb26-38"><a href="the-multinomial-logit-model.html#cb26-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb26-39"><a href="the-multinomial-logit-model.html#cb26-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="fu">expression</span>(beta)) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Likelihood Function Value&quot;</span>) <span class="sc">+</span></span>
<span id="cb26-40"><a href="the-multinomial-logit-model.html#cb26-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(likelihood <span class="sc">~</span> ., <span class="at">scales =</span> <span class="st">&quot;free_y&quot;</span>)  <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span id="fig:demo-likelihood"></span>
<img src="04-mnl_files/figure-html/demo-likelihood-1.png" alt="Likelihood and log-likelihood as a function of a parameter value." width="672" />
<p class="caption">
Figure 4.5: Likelihood and log-likelihood as a function of a parameter value.
</p>
</div>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>These include numerical problems, because the MNP can only
be calculated using multi-dimensional integration, and problems of
interpretation. A special case of the MNP, when the error terms are distributed
independently (no covariance) and identically (same variance), obtains
estimation and prediction results that are very similar to those for the MNL
model.<a href="the-multinomial-logit-model.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>A model for which the probability can be calculated without
use of numerical integration or simulation methods.<a href="the-multinomial-logit-model.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>The exponent of a summation, <span class="math inline">\(\exp(A+B)\)</span>, is equal to the product of
the exponents of the elements in the sum, <span class="math inline">\(\\exp(A) \exp(B)\)</span> .<a href="the-multinomial-logit-model.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>We use tables to illustrate calculation of the utility
values and MNL probabilities. The first column shows the specification
expression with appropriate values for variables and parameters, the second
shows the calculated utility value, the third shows the exponent of the utility
including the sum of the exponents, and the fourth shows the probability values.<a href="the-multinomial-logit-model.html#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>This example ignores the increase in bus service frequency which
might increase the probability of persons choosing bus; however, the increase is
unlikely to be of the magnitude suggested by the IIA property.<a href="the-multinomial-logit-model.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>In this case, we show the preservation of probabilities for the
individual. In general, the individual probabilities are expected to change.<a href="the-multinomial-logit-model.html#fnref6" class="footnote-back">↩︎</a></p></li>
<li id="fn7"><p>Interested readers are referred to train (1986) for a
derivation and proof.<a href="the-multinomial-logit-model.html#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p>As before, interested readers are referred to Train (1986)
for derivation and proof.<a href="the-multinomial-logit-model.html#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p>This comparison is independent of which alternative
is chosen as the reference alternative since the effect of changing the
reference alternative will be to increase each parameter by the same value.<a href="the-multinomial-logit-model.html#fnref9" class="footnote-back">↩︎</a></p></li>
<li id="fn10"><p>Iso-utility lines connect all points for which the values of
time and cost result in the same utility. The slope of these lines equals the
inverse of the value of time, <span class="math inline">\(\beta_1/\beta_2\)</span>.<a href="the-multinomial-logit-model.html#fnref10" class="footnote-back">↩︎</a></p></li>
<li id="fn11"><p>Dependence of <span class="math inline">\(P_{j&#39;t}\)</span> on <span class="math inline">\(b\)</span> is made implicit to simplify
notation.<a href="the-multinomial-logit-model.html#fnref11" class="footnote-back">↩︎</a></p></li>
<li id="fn12"><p>Dependence of <span class="math inline">\(P_{j&#39;t}\)</span> on <span class="math inline">\(b\)</span> is made implicit to simplify
notation.<a href="the-multinomial-logit-model.html#fnref12" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="utility-based-choice-theory.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estimation-chapter.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
